// ============================================================
// ASSETS DUMMY DATA
// Oil & Gas Operations Management Platform — ADI
// ============================================================

export type AssetCategory =
  | 'well_control'
  | 'hoisting'
  | 'rotating'
  | 'circulating'
  | 'power_generation'
  | 'structural'
  | 'lifting'
  | 'drill_string'
  | 'safety_equipment'
  | 'instrumentation'
  | 'vehicles';

export type AssetStatus =
  | 'active'
  | 'in_service'
  | 'out_of_service'
  | 'maintenance'
  | 'inspection_due'
  | 'quarantine'
  | 'scrapped'
  | 'on_order';

export type InspectionResult = 'pass' | 'conditional_pass' | 'fail' | 'pending';

export interface AssetCertificate {
  id: string;
  type: string;
  issuedBy: string;
  issuedDate: string;
  expiryDate: string;
  certificateNumber: string;
  status: 'valid' | 'expiring_soon' | 'expired';
}

export interface AssetInspectionRecord {
  id: string;
  date: string;
  type: string;
  inspectedBy: string;
  result: InspectionResult;
  findings: string;
  nextInspectionDate: string;
  reportRef: string;
}

export interface AssetMaintenanceRecord {
  id: string;
  date: string;
  type: 'preventive' | 'corrective' | 'overhaul' | 'modification';
  description: string;
  performedBy: string;
  workOrderId: string;
  partsUsed: string[];
  laborHours: number;
  cost: number;
  nextPMDate: string;
}

export interface AssetSpecification {
  key: string;
  value: string;
  unit?: string;
}

export interface Asset {
  id: string;
  assetTag: string;
  description: string;
  category: AssetCategory;
  status: AssetStatus;
  rigId: string | null;
  rigName: string | null;
  location: string;
  manufacturer: string;
  model: string;
  serialNumber: string;
  partNumber?: string;
  purchaseDate: string;
  purchaseCost: number;
  currentValue: number;
  expectedLifeYears: number;
  ageYears: number;
  serviceHours?: number;
  maxServiceHours?: number;
  lastInspectionDate: string;
  nextInspectionDate: string;
  lastPMDate: string;
  nextPMDate: string;
  certificationExpiryDate?: string;
  specifications: AssetSpecification[];
  certificates: AssetCertificate[];
  inspectionHistory: AssetInspectionRecord[];
  maintenanceHistory: AssetMaintenanceRecord[];
  associatedNcoIds: string[];
  associatedMocIds: string[];
  tags: string[];
  notes?: string;
}

export const ASSETS: Asset[] = [
  // ── RIG ALPHA (AD-201) ─────────────────────────────────────────────
  {
    id: 'AD-201-BOP-001',
    assetTag: 'AD-201-BOP-001',
    description: 'Shaffer 13-5/8" 10,000 PSI 4-Ram BOP Stack — Primary Well Control Unit',
    category: 'well_control',
    status: 'in_service',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    location: 'Well ADB-47 — Wellhead',
    manufacturer: 'National Oilwell Varco (Shaffer)',
    model: 'Shaffer Type SL',
    serialNumber: 'SHF-SL-2019-0047',
    partNumber: 'NOV-BOP-SL-13-10K',
    purchaseDate: '2019-08-01',
    purchaseCost: 2850000,
    currentValue: 1850000,
    expectedLifeYears: 25,
    ageYears: 6,
    lastInspectionDate: '2024-08-15',
    nextInspectionDate: '2026-08-15',
    lastPMDate: '2025-01-10',
    nextPMDate: '2026-01-10',
    certificationExpiryDate: '2026-08-31',
    specifications: [
      { key: 'Bore Size', value: '13-5/8', unit: 'inches' },
      { key: 'Working Pressure', value: '10,000', unit: 'PSI' },
      { key: 'Test Pressure', value: '15,000', unit: 'PSI' },
      { key: 'Temperature Rating', value: 'U (−20°F to 250°F)', unit: '' },
      { key: 'Number of Rams', value: '4', unit: 'units' },
      { key: 'Ram Configuration', value: 'Pipe / Blind-Shear / Pipe / Variable Bore', unit: '' },
      { key: 'H2S Service', value: 'Yes — NACE MR0175', unit: '' },
      { key: 'API Standard', value: 'API 16A 3rd Edition', unit: '' },
      { key: 'Stack Height', value: '4.2', unit: 'm' },
      { key: 'Stack Weight', value: '28,400', unit: 'kg' },
      { key: 'Accumulator Bottles', value: '12', unit: 'units' },
      { key: 'Closing Time (blind-shear)', value: '≤30', unit: 'seconds' },
    ],
    certificates: [
      {
        id: 'CERT-BOP001-001',
        type: 'API 16A Monogram Certificate',
        issuedBy: 'API',
        issuedDate: '2019-08-01',
        expiryDate: '2026-08-31',
        certificateNumber: 'API-16A-SHF-2019-0047',
        status: 'valid',
      },
      {
        id: 'CERT-BOP001-002',
        type: 'Pressure Test Certificate — 5-Year Overhaul',
        issuedBy: 'Bureau Veritas',
        issuedDate: '2019-08-15',
        expiryDate: '2024-08-15',
        certificateNumber: 'BV-PT-2019-AD201-BOP',
        status: 'expired',
      },
      {
        id: 'CERT-BOP001-003',
        type: 'NACE MR0175 Sour Service Certification',
        issuedBy: 'TÜV Rheinland',
        issuedDate: '2019-07-20',
        expiryDate: '2027-07-20',
        certificateNumber: 'TUV-NACE-2019-0047',
        status: 'valid',
      },
    ],
    inspectionHistory: [
      {
        id: 'INSP-BOP001-001',
        date: '2024-08-15',
        type: '5-Year Full Inspection & Recertification',
        inspectedBy: 'NOV Field Engineering / TÜV Rheinland',
        result: 'pass',
        findings: 'All rams sealing element replaced. Accumulator bladders replaced (all 12). Hydraulic system flushed and refilled. Blind-shear blade sharpness within spec. Pressure test to 15,000 PSI held 5 minutes — no pressure drop. Full function test on all rams: pass.',
        nextInspectionDate: '2026-08-15',
        reportRef: 'NOV-INSP-AD201-BOP001-AUG2024.pdf',
      },
      {
        id: 'INSP-BOP001-002',
        date: '2025-01-10',
        type: 'Annual API 16A Inspection',
        inspectedBy: 'Emma Richards (QE)',
        result: 'pass',
        findings: 'Weekly BOP function tests reviewed — all pass. Accumulator pre-charge at 1,250 PSI — within specification. Visual inspection of all hydraulic connections — no leaks. Ram visual inspection through bore — no damage observed.',
        nextInspectionDate: '2026-01-10',
        reportRef: 'ADI-INSP-AD201-BOP001-JAN2025.pdf',
      },
    ],
    maintenanceHistory: [
      {
        id: 'PM-BOP001-001',
        date: '2024-08-15',
        type: 'overhaul',
        description: '5-Year Major Overhaul — All sealing elements replaced, accumulator bladders replaced, hydraulic fluid flush, dimensional inspection of all bore-critical components.',
        performedBy: 'NOV Field Engineering — Field Engineer Mike Thompson',
        workOrderId: 'WO-2024-AD201-0845',
        partsUsed: ['NOV-SL-SEAL-KIT-13-10K', 'NOV-ACC-BLADDER x12', 'NOV-HYD-FLUID-5GAL x10'],
        laborHours: 96,
        cost: 185000,
        nextPMDate: '2025-08-15',
      },
      {
        id: 'PM-BOP001-002',
        date: '2025-01-10',
        type: 'preventive',
        description: 'Annual PM — Hydraulic system pressure check, accumulator pre-charge verification, visual inspection of all rams and connections. Weekly test records verified.',
        performedBy: 'Khalid Mahmoud (Maintenance Manager)',
        workOrderId: 'WO-2025-AD201-0102',
        partsUsed: [],
        laborHours: 8,
        cost: 3500,
        nextPMDate: '2026-01-10',
      },
    ],
    associatedNcoIds: ['NCO-2024-043'],
    associatedMocIds: ['MOC-2025-001'],
    tags: ['BOP', 'Well Control', 'Shaffer', 'Critical Equipment', 'API 16A', 'Rig Alpha'],
    notes: '5-year overhaul due August 2026. REQ-2024-161 raised for overhaul scheduling. MOC-2025-001 adds additional pipe ram to this stack.',
  },
  {
    id: 'AD-201-TDS-001',
    assetTag: 'AD-201-TDS-001',
    description: 'Varco TDS-11SA Top Drive System',
    category: 'rotating',
    status: 'in_service',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    location: 'Well ADB-47 — Derrick',
    manufacturer: 'National Oilwell Varco',
    model: 'TDS-11SA',
    serialNumber: 'NOV-TDS11SA-2020-0178',
    purchaseDate: '2020-03-15',
    purchaseCost: 1650000,
    currentValue: 1100000,
    expectedLifeYears: 20,
    ageYears: 5,
    serviceHours: 18450,
    maxServiceHours: 40000,
    lastInspectionDate: '2025-01-08',
    nextInspectionDate: '2025-07-08',
    lastPMDate: '2025-01-08',
    nextPMDate: '2025-04-08',
    specifications: [
      { key: 'Rating', value: '500', unit: 'ton' },
      { key: 'Motor HP', value: '1,100', unit: 'HP' },
      { key: 'Max RPM', value: '250', unit: 'RPM' },
      { key: 'Max Torque', value: '37,500', unit: 'ft-lb' },
      { key: 'Make/Break Torque', value: '100,000', unit: 'ft-lb' },
      { key: 'Connection', value: '6-5/8" API IF Box', unit: '' },
      { key: 'Weight', value: '8,200', unit: 'kg' },
      { key: 'Gearbox Oil Capacity', value: '120', unit: 'litres' },
      { key: 'Oil Type', value: 'ISO VG 220 Gear Oil', unit: '' },
    ],
    certificates: [
      {
        id: 'CERT-TDS001-001',
        type: 'NOV Factory Acceptance Test Certificate',
        issuedBy: 'NOV Manufacturing',
        issuedDate: '2020-03-01',
        expiryDate: '2030-03-01',
        certificateNumber: 'NOV-FAT-TDS11SA-2020-0178',
        status: 'valid',
      },
    ],
    inspectionHistory: [
      {
        id: 'INSP-TDS001-001',
        date: '2025-01-08',
        type: 'NCO-driven inspection — gearbox filter failure investigation',
        inspectedBy: 'Khalid Mahmoud / Intertek',
        result: 'conditional_pass',
        findings: 'Filter element failure (sub-spec element installed — NCO-2025-001). Oil analysis elevated iron at 850 ppm. Correct OEM filter installed. Oil flush performed. New oil charge installed. Re-test oil analysis: 145 ppm iron — within normal range. Top drive returned to full service.',
        nextInspectionDate: '2025-07-08',
        reportRef: 'Intertek-OilAnalysis-AD201-TDS-Jan2025.pdf',
      },
    ],
    maintenanceHistory: [
      {
        id: 'PM-TDS001-001',
        date: '2025-01-08',
        type: 'corrective',
        description: 'Emergency oil filter replacement following NCO-2025-001. Sub-spec filter removed, OEM filter (P/N 60220-0000) installed. Full oil flush performed. New ISO VG 220 oil charge installed.',
        performedBy: 'Khalid Mahmoud',
        workOrderId: 'WO-2025-AD201-0108',
        partsUsed: ['NOV-60220-0000 (OEM Filter)', 'ISO-VG220-25L x5'],
        laborHours: 12,
        cost: 24500,
        nextPMDate: '2025-04-08',
      },
    ],
    associatedNcoIds: ['NCO-2025-001'],
    associatedMocIds: [],
    tags: ['Top Drive', 'NOV', 'Rotating Equipment', 'Rig Alpha', 'TDS-11SA'],
  },
  {
    id: 'AD-201-MDP-001',
    assetTag: 'AD-201-MDP-001',
    description: 'National 12-P-160 Triplex Mud Pump #1',
    category: 'circulating',
    status: 'in_service',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    location: 'Well ADB-47 — Pump House',
    manufacturer: 'National Oilwell Varco',
    model: 'National 12-P-160',
    serialNumber: 'NAT-12P160-2020-0045',
    purchaseDate: '2020-03-15',
    purchaseCost: 750000,
    currentValue: 480000,
    expectedLifeYears: 20,
    ageYears: 5,
    serviceHours: 22100,
    maxServiceHours: 50000,
    lastInspectionDate: '2025-11-15',
    nextInspectionDate: '2026-05-15',
    lastPMDate: '2025-11-15',
    nextPMDate: '2026-02-15',
    specifications: [
      { key: 'Stroke Rating', value: '160', unit: 'strokes/min' },
      { key: 'Liner Size (current)', value: '6.5', unit: 'inches' },
      { key: 'Output Rate (max)', value: '1,120', unit: 'gpm' },
      { key: 'Working Pressure (max)', value: '5,000', unit: 'PSI' },
      { key: 'Input Power', value: '1,600', unit: 'HP' },
      { key: 'Rod Load Rating', value: '162,000', unit: 'lbs' },
      { key: 'Piston Liner Type', value: 'Chrome Carbide', unit: '' },
      { key: 'Current Liner Life', value: '78', unit: '% used' },
    ],
    certificates: [],
    inspectionHistory: [
      {
        id: 'INSP-MDP001-001',
        date: '2025-11-15',
        type: '6-Month PM Inspection',
        inspectedBy: 'Sami Al-Otaibi',
        result: 'conditional_pass',
        findings: 'Liner wear at 78% of service life. Valves showing normal wear. Pulsation dampener pre-charge at 80 PSI (correct). Gear end oil clean — no contamination. Recommended liner replacement at next maintenance window.',
        nextInspectionDate: '2026-05-15',
        reportRef: 'PM-AD201-MDP001-Nov2025.pdf',
      },
    ],
    maintenanceHistory: [
      {
        id: 'PM-MDP001-001',
        date: '2025-11-15',
        type: 'preventive',
        description: '6-Month PM — Valve and liner inspection, gear end oil sample, pulsation dampener check, crosshead pin lubrication.',
        performedBy: 'Sami Al-Otaibi',
        workOrderId: 'WO-2025-AD201-1108',
        partsUsed: ['NAT-12P-VALVE-SET', 'Gear Oil Sample Bottle'],
        laborHours: 16,
        cost: 8500,
        nextPMDate: '2026-02-15',
      },
    ],
    associatedNcoIds: [],
    associatedMocIds: ['MOC-2025-003'],
    tags: ['Mud Pump', 'Circulating System', 'National 12-P-160', 'Rig Alpha'],
    notes: 'DRQ-2026-006 raised for liner replacement. Liner sets on order.',
  },
  {
    id: 'AD-201-MDP-002',
    assetTag: 'AD-201-MDP-002',
    description: 'National 12-P-160 Triplex Mud Pump #2',
    category: 'circulating',
    status: 'in_service',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    location: 'Well ADB-47 — Pump House',
    manufacturer: 'National Oilwell Varco',
    model: 'National 12-P-160',
    serialNumber: 'NAT-12P160-2020-0046',
    purchaseDate: '2020-03-15',
    purchaseCost: 750000,
    currentValue: 480000,
    expectedLifeYears: 20,
    ageYears: 5,
    serviceHours: 19800,
    lastInspectionDate: '2025-11-15',
    nextInspectionDate: '2026-05-15',
    lastPMDate: '2025-11-15',
    nextPMDate: '2026-02-15',
    specifications: [
      { key: 'Stroke Rating', value: '160', unit: 'strokes/min' },
      { key: 'Liner Size (current)', value: '6.5', unit: 'inches' },
      { key: 'Working Pressure (max)', value: '5,000', unit: 'PSI' },
      { key: 'Input Power', value: '1,600', unit: 'HP' },
    ],
    certificates: [],
    inspectionHistory: [],
    maintenanceHistory: [],
    associatedNcoIds: [],
    associatedMocIds: [],
    tags: ['Mud Pump', 'Circulating System', 'National 12-P-160', 'Rig Alpha'],
  },
  {
    id: 'AD-201-MDP-003',
    assetTag: 'AD-201-MDP-003',
    description: 'National 12-P-160 Triplex Mud Pump #3 (Standby)',
    category: 'circulating',
    status: 'in_service',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    location: 'Well ADB-47 — Pump House',
    manufacturer: 'National Oilwell Varco',
    model: 'National 12-P-160',
    serialNumber: 'NAT-12P160-2020-0047',
    purchaseDate: '2020-03-15',
    purchaseCost: 750000,
    currentValue: 520000,
    expectedLifeYears: 20,
    ageYears: 5,
    serviceHours: 8200,
    lastInspectionDate: '2025-11-15',
    nextInspectionDate: '2026-05-15',
    lastPMDate: '2025-11-15',
    nextPMDate: '2026-05-15',
    specifications: [
      { key: 'Stroke Rating', value: '160', unit: 'strokes/min' },
      { key: 'Working Pressure (max)', value: '5,000', unit: 'PSI' },
      { key: 'Input Power', value: '1,600', unit: 'HP' },
    ],
    certificates: [],
    inspectionHistory: [],
    maintenanceHistory: [],
    associatedNcoIds: [],
    associatedMocIds: [],
    tags: ['Mud Pump', 'Standby', 'Circulating System', 'Rig Alpha'],
  },
  {
    id: 'AD-201-DWK-001',
    assetTag: 'AD-201-DWK-001',
    description: 'National 14-P-220 Drawworks — Main Hoisting Unit',
    category: 'hoisting',
    status: 'in_service',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    location: 'Well ADB-47 — Substructure',
    manufacturer: 'National Oilwell Varco',
    model: 'National 14-P-220',
    serialNumber: 'NAT-14P220-2018-0021',
    purchaseDate: '2018-06-01',
    purchaseCost: 2200000,
    currentValue: 1350000,
    expectedLifeYears: 25,
    ageYears: 7,
    lastInspectionDate: '2025-08-01',
    nextInspectionDate: '2026-08-01',
    lastPMDate: '2025-11-01',
    nextPMDate: '2026-02-01',
    specifications: [
      { key: 'Input Power', value: '2,000', unit: 'HP' },
      { key: 'Maximum Hookload', value: '450', unit: 'ton' },
      { key: 'Drum Capacity', value: '2,200m of 1-5/8" Wire', unit: '' },
      { key: 'Fast Line Speed (max)', value: '1.8', unit: 'm/s' },
      { key: 'Brake Type', value: 'Water-cooled Hydrodynamic + Electro-magnetic', unit: '' },
    ],
    certificates: [],
    inspectionHistory: [],
    maintenanceHistory: [],
    associatedNcoIds: [],
    associatedMocIds: ['MOC-2026-004', 'MOC-2026-005'],
    tags: ['Drawworks', 'Hoisting', 'National 14-P-220', 'Rig Alpha'],
    notes: 'MOC-2026-004: rotary table bearing replaced emergency. MOC-2026-005: CrownSaver upgrade planned May 2026.',
  },
  {
    id: 'AD-201-RTB-001',
    assetTag: 'AD-201-RTB-001',
    description: 'National 14-P-220 Rotary Table',
    category: 'rotating',
    status: 'in_service',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    location: 'Well ADB-47 — Drill Floor',
    manufacturer: 'National Oilwell Varco',
    model: 'National 14-P-220 Rotary',
    serialNumber: 'NAT-RTB-2018-0021',
    purchaseDate: '2018-06-01',
    purchaseCost: 480000,
    currentValue: 280000,
    expectedLifeYears: 20,
    ageYears: 7,
    serviceHours: 31200,
    lastInspectionDate: '2026-02-26',
    nextInspectionDate: '2026-08-26',
    lastPMDate: '2026-02-26',
    nextPMDate: '2026-05-26',
    specifications: [
      { key: 'Table Opening', value: '27-1/2', unit: 'inches' },
      { key: 'Torque Rating', value: '40,000', unit: 'ft-lb' },
      { key: 'Speed Range', value: '0–200', unit: 'RPM' },
      { key: 'Load Rating', value: '450', unit: 'ton' },
      { key: 'Primary Bearing Type', value: 'SKF 23256 CACK/W33 Spherical Roller', unit: '' },
    ],
    certificates: [],
    inspectionHistory: [
      {
        id: 'INSP-RTB001-001',
        date: '2026-02-26',
        type: 'Emergency Inspection — Bearing Failure',
        inspectedBy: 'Khalid Mahmoud',
        result: 'conditional_pass',
        findings: 'Primary bearing failed — abnormal vibration and knock. Bearing replaced with SKF 23256 CACK/W33 per MOC-2026-004. Function test post-replacement: normal vibration levels. Returned to service.',
        nextInspectionDate: '2026-08-26',
        reportRef: 'MOC-2026-004-PostInstall-Report.pdf',
      },
    ],
    maintenanceHistory: [
      {
        id: 'PM-RTB001-001',
        date: '2026-02-26',
        type: 'corrective',
        description: 'Emergency bearing replacement per MOC-2026-004. SKF 23256 CACK/W33 spherical roller bearing installed. Full function test completed.',
        performedBy: 'Khalid Mahmoud / Sami Al-Otaibi',
        workOrderId: 'WO-2026-AD201-0226-EMRG',
        partsUsed: ['SKF-23256-CACK-W33 Bearing'],
        laborHours: 18,
        cost: 45000,
        nextPMDate: '2026-05-26',
      },
    ],
    associatedNcoIds: [],
    associatedMocIds: ['MOC-2026-004'],
    tags: ['Rotary Table', 'Rotating Equipment', 'Rig Alpha', 'Emergency Repair'],
  },
  {
    id: 'AD-201-GEN-001',
    assetTag: 'AD-201-GEN-001',
    description: 'Caterpillar 3516B Main Generator Set #1 — 1,800 kW',
    category: 'power_generation',
    status: 'in_service',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    location: 'Well ADB-47 — Generator House',
    manufacturer: 'Caterpillar',
    model: '3516B',
    serialNumber: 'CAT-3516B-2018-ADI01',
    purchaseDate: '2018-06-01',
    purchaseCost: 680000,
    currentValue: 380000,
    expectedLifeYears: 20,
    ageYears: 7,
    serviceHours: 42800,
    maxServiceHours: 80000,
    lastInspectionDate: '2025-09-01',
    nextInspectionDate: '2026-03-01',
    lastPMDate: '2025-09-01',
    nextPMDate: '2026-03-01',
    certificationExpiryDate: '2026-09-30',
    specifications: [
      { key: 'Power Output (prime)', value: '1,800', unit: 'kW' },
      { key: 'Fuel Type', value: 'Diesel', unit: '' },
      { key: 'Alternator Voltage', value: '480V / 3-phase / 60Hz', unit: '' },
      { key: 'Engine RPM', value: '1,800', unit: 'RPM' },
      { key: 'Fuel Consumption (full load)', value: '380', unit: 'litres/hour' },
    ],
    certificates: [
      {
        id: 'CERT-GEN001-001',
        type: 'Annual Electrical Safety Certificate',
        issuedBy: 'Saudi Electrical Safety Authority',
        issuedDate: '2025-09-01',
        expiryDate: '2026-09-30',
        certificateNumber: 'SESA-GEN-2025-AD201-01',
        status: 'valid',
      },
    ],
    inspectionHistory: [],
    maintenanceHistory: [],
    associatedNcoIds: [],
    associatedMocIds: [],
    tags: ['Generator', 'Power Generation', 'Caterpillar 3516B', 'Rig Alpha'],
  },
  {
    id: 'AD-201-CRN-001',
    assetTag: 'AD-201-CRN-001',
    description: 'National Oilwell Varco NC-4016H Pedestal Crane — Main Crane',
    category: 'lifting',
    status: 'in_service',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    location: 'Well ADB-47 — Rig Floor Pedestal',
    manufacturer: 'National Oilwell Varco',
    model: 'NC-4016H',
    serialNumber: 'NOV-NC4016H-2018-AD201',
    purchaseDate: '2018-06-01',
    purchaseCost: 320000,
    currentValue: 185000,
    expectedLifeYears: 20,
    ageYears: 7,
    lastInspectionDate: '2024-12-28',
    nextInspectionDate: '2025-12-28',
    lastPMDate: '2024-12-28',
    nextPMDate: '2025-06-28',
    certificationExpiryDate: '2025-12-31',
    specifications: [
      { key: 'SWL (max)', value: '25', unit: 'ton' },
      { key: 'Max Radius', value: '16', unit: 'm' },
      { key: 'Boom Length', value: '18', unit: 'm' },
      { key: 'Slew Range', value: '360°', unit: '' },
    ],
    certificates: [
      {
        id: 'CERT-CRN001-001',
        type: 'Annual Load Test Certificate',
        issuedBy: 'Bureau Veritas',
        issuedDate: '2024-12-28',
        expiryDate: '2025-12-31',
        certificateNumber: 'BV-CRANE-2024-AD201-001',
        status: 'expiring_soon',
      },
    ],
    inspectionHistory: [
      {
        id: 'INSP-CRN001-001',
        date: '2024-12-28',
        type: 'Annual Statutory Load Test and Inspection',
        inspectedBy: 'Bureau Veritas — Inspector J. Al-Haddad',
        result: 'pass',
        findings: 'SWL 110% load test (27.5 ton): PASS. Wire rope inspection — acceptable. All safety devices operational (anti-two-block, load moment indicator, emergency stop). No structural defects found.',
        nextInspectionDate: '2025-12-28',
        reportRef: 'BV-CraneReport-AD201-CRN001-Dec2024.pdf',
      },
    ],
    maintenanceHistory: [],
    associatedNcoIds: [],
    associatedMocIds: [],
    tags: ['Crane', 'Lifting Equipment', 'NOV', 'Rig Alpha', 'Certified'],
  },
  {
    id: 'AD-201-CRN-002',
    assetTag: 'AD-201-CRN-002',
    description: 'Liebherr LTM 1060 Mobile Crane — Auxiliary',
    category: 'lifting',
    status: 'in_service',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    location: 'Well ADB-47 — Laydown Area',
    manufacturer: 'Liebherr',
    model: 'LTM 1060-3.1',
    serialNumber: 'LBH-LTM1060-2021-0098',
    purchaseDate: '2021-02-10',
    purchaseCost: 1850000,
    currentValue: 1300000,
    expectedLifeYears: 20,
    ageYears: 4,
    lastInspectionDate: '2024-12-28',
    nextInspectionDate: '2025-12-28',
    lastPMDate: '2025-06-01',
    nextPMDate: '2025-12-01',
    certificationExpiryDate: '2025-12-31',
    specifications: [
      { key: 'SWL (max)', value: '60', unit: 'ton' },
      { key: 'Max Radius', value: '22', unit: 'm' },
      { key: 'Boom Length (max)', value: '35', unit: 'm' },
    ],
    certificates: [
      {
        id: 'CERT-CRN002-001',
        type: 'Annual Load Test Certificate',
        issuedBy: 'Bureau Veritas',
        issuedDate: '2024-12-28',
        expiryDate: '2025-12-31',
        certificateNumber: 'BV-CRANE-2024-AD201-002',
        status: 'expiring_soon',
      },
    ],
    inspectionHistory: [],
    maintenanceHistory: [],
    associatedNcoIds: [],
    associatedMocIds: [],
    tags: ['Mobile Crane', 'Lifting', 'Liebherr', 'Rig Alpha'],
  },
  {
    id: 'AD-201-SHA-001',
    assetTag: 'AD-201-SHA-001',
    description: 'Derrick FLC 500 Shale Shaker #1',
    category: 'circulating',
    status: 'in_service',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    location: 'Well ADB-47 — Shaker House',
    manufacturer: 'Derrick Equipment Company',
    model: 'FLC 500',
    serialNumber: 'DEC-FLC500-2020-AD201-01',
    purchaseDate: '2020-03-15',
    purchaseCost: 85000,
    currentValue: 55000,
    expectedLifeYears: 15,
    ageYears: 5,
    serviceHours: 19200,
    lastInspectionDate: '2025-11-15',
    nextInspectionDate: '2026-05-15',
    lastPMDate: '2025-11-15',
    nextPMDate: '2026-02-15',
    specifications: [
      { key: 'G-Force', value: '4.8', unit: 'G' },
      { key: 'Motion Type', value: 'Linear', unit: '' },
      { key: 'Screen Area', value: '2.97', unit: 'm²' },
      { key: 'Screen Size', value: 'API 100 mesh (standard)', unit: '' },
      { key: 'Feed Capacity', value: '1,100', unit: 'gpm' },
    ],
    certificates: [],
    inspectionHistory: [],
    maintenanceHistory: [],
    associatedNcoIds: [],
    associatedMocIds: [],
    tags: ['Shale Shaker', 'Solids Control', 'Derrick FLC 500', 'Rig Alpha'],
  },

  // ── RIG BRAVO (AD-202) ─────────────────────────────────────────────
  {
    id: 'AD-202-BOP-001',
    assetTag: 'AD-202-BOP-001',
    description: 'Cameron 13-5/8" 10,000 PSI 4-Ram BOP Stack',
    category: 'well_control',
    status: 'in_service',
    rigId: 'AD-202',
    rigName: 'Rig Bravo',
    location: 'Well ADB-52 — Wellhead',
    manufacturer: 'Cameron (SLB)',
    model: 'Cameron Type U',
    serialNumber: 'CAM-U-2020-0082',
    purchaseDate: '2020-05-01',
    purchaseCost: 2950000,
    currentValue: 2200000,
    expectedLifeYears: 25,
    ageYears: 5,
    lastInspectionDate: '2025-05-10',
    nextInspectionDate: '2027-05-10',
    lastPMDate: '2025-11-10',
    nextPMDate: '2026-05-10',
    certificationExpiryDate: '2027-05-31',
    specifications: [
      { key: 'Bore Size', value: '13-5/8', unit: 'inches' },
      { key: 'Working Pressure', value: '10,000', unit: 'PSI' },
      { key: 'Ram Configuration', value: 'Pipe / Blind-Shear / Pipe / Variable Bore', unit: '' },
      { key: 'H2S Service', value: 'Yes — NACE MR0175', unit: '' },
      { key: 'API Standard', value: 'API 16A 3rd Edition', unit: '' },
    ],
    certificates: [
      {
        id: 'CERT-AD202BOP-001',
        type: '5-Year Overhaul Certificate',
        issuedBy: 'Cameron Field Services',
        issuedDate: '2025-05-10',
        expiryDate: '2027-05-10',
        certificateNumber: 'CAM-OVH-2025-AD202',
        status: 'valid',
      },
    ],
    inspectionHistory: [],
    maintenanceHistory: [],
    associatedNcoIds: [],
    associatedMocIds: [],
    tags: ['BOP', 'Well Control', 'Cameron', 'Critical Equipment', 'Rig Bravo'],
  },
  {
    id: 'AD-202-MAS-001',
    assetTag: 'AD-202-MAS-001',
    description: 'Rig Bravo Derrick / Mast Structure — 185ft API Derrick',
    category: 'structural',
    status: 'inspection_due',
    rigId: 'AD-202',
    rigName: 'Rig Bravo',
    location: 'Well ADB-52 — Wellsite',
    manufacturer: 'Bentec',
    model: 'BT-185-500',
    serialNumber: 'BENT-BT185-2020-AD202',
    purchaseDate: '2020-05-01',
    purchaseCost: 3800000,
    currentValue: 2900000,
    expectedLifeYears: 30,
    ageYears: 5,
    lastInspectionDate: '2025-01-15',
    nextInspectionDate: '2026-01-15',
    lastPMDate: '2025-01-15',
    nextPMDate: '2026-01-15',
    specifications: [
      { key: 'Height', value: '185', unit: 'ft (56.4m)' },
      { key: 'Static Hook Load Rating', value: '500', unit: 'ton' },
      { key: 'Wind Load Rating', value: '125', unit: 'mph' },
      { key: 'API Standard', value: 'API 4F', unit: '' },
    ],
    certificates: [],
    inspectionHistory: [
      {
        id: 'INSP-AD202MAS-001',
        date: '2025-01-15',
        type: 'Annual Structural Inspection',
        inspectedBy: 'Bureau Veritas',
        result: 'conditional_pass',
        findings: 'Substandard weld identified on secondary leg brace at elevation 24m (NCO-2025-002). Hookload restricted to 350 ton pending structural repair assessment. All other structural elements within specification.',
        nextInspectionDate: '2026-01-15',
        reportRef: 'BV-StructuralInsp-AD202-MAS001-Jan2025.pdf',
      },
    ],
    maintenanceHistory: [],
    associatedNcoIds: ['NCO-2025-002'],
    associatedMocIds: [],
    tags: ['Derrick', 'Structural', 'Bentec', 'Rig Bravo', 'Restricted'],
    notes: 'RESTRICTION: Max hookload limited to 350 ton until NCO-2025-002 resolved. Weld repair pending.',
  },
  {
    id: 'AD-202-TDS-001',
    assetTag: 'AD-202-TDS-001',
    description: 'Varco TDS-11SA Top Drive System',
    category: 'rotating',
    status: 'in_service',
    rigId: 'AD-202',
    rigName: 'Rig Bravo',
    location: 'Well ADB-52 — Derrick',
    manufacturer: 'National Oilwell Varco',
    model: 'TDS-11SA',
    serialNumber: 'NOV-TDS11SA-2020-0201',
    purchaseDate: '2020-05-01',
    purchaseCost: 1650000,
    currentValue: 1120000,
    expectedLifeYears: 20,
    ageYears: 5,
    serviceHours: 21400,
    lastInspectionDate: '2025-05-01',
    nextInspectionDate: '2025-11-01',
    lastPMDate: '2025-11-01',
    nextPMDate: '2026-02-01',
    specifications: [
      { key: 'Rating', value: '500', unit: 'ton' },
      { key: 'Motor HP', value: '1,250', unit: 'HP' },
      { key: 'Max Torque', value: '40,000', unit: 'ft-lb' },
    ],
    certificates: [],
    inspectionHistory: [],
    maintenanceHistory: [],
    associatedNcoIds: [],
    associatedMocIds: [],
    tags: ['Top Drive', 'NOV', 'Rotating Equipment', 'Rig Bravo'],
  },
  {
    id: 'AD-202-KLN-001',
    assetTag: 'AD-202-KLN-001',
    description: '3" 10,000 PSI Kill Line Manifold Assembly — Surface BOP',
    category: 'well_control',
    status: 'in_service',
    rigId: 'AD-202',
    rigName: 'Rig Bravo',
    location: 'Well ADB-52 — Wellhead Area',
    manufacturer: 'Forum Energy Technologies',
    model: 'FET KLM-3-10K',
    serialNumber: 'FET-KLM-2020-AD202',
    purchaseDate: '2020-05-01',
    purchaseCost: 185000,
    currentValue: 135000,
    expectedLifeYears: 20,
    ageYears: 5,
    lastInspectionDate: '2025-08-25',
    nextInspectionDate: '2026-02-25',
    lastPMDate: '2025-08-25',
    nextPMDate: '2026-08-25',
    specifications: [
      { key: 'Pipe Size', value: '3', unit: 'inches' },
      { key: 'Working Pressure', value: '10,000', unit: 'PSI' },
      { key: 'Test Standard', value: 'ASME B31.3 Class 3', unit: '' },
      { key: 'Material', value: 'AISI 4130 Alloy Steel', unit: '' },
    ],
    certificates: [],
    inspectionHistory: [
      {
        id: 'INSP-AD202KLN-001',
        date: '2025-08-25',
        type: 'NCO-driven RT inspection — Weld defect investigation',
        inspectedBy: 'TÜV Rheinland NDT',
        result: 'fail',
        findings: 'Gas porosity cluster and 25mm linear indication in manifold weld #3. Exceeds ASME B31.3 acceptance criteria. Defective section removed and re-welded by 6GR certified welder. Re-test RT: PASS.',
        nextInspectionDate: '2026-02-25',
        reportRef: 'RT-Report-KillLine-AD202-Aug2025.pdf',
      },
    ],
    maintenanceHistory: [],
    associatedNcoIds: ['NCO-2025-009'],
    associatedMocIds: [],
    tags: ['Kill Line', 'Well Control', 'High Pressure', 'Rig Bravo', 'Weld Repair'],
  },
  {
    id: 'AD-202-GEN-001',
    assetTag: 'AD-202-GEN-001',
    description: 'Caterpillar 3516C Main Generator Set #1 — 2,000 kW',
    category: 'power_generation',
    status: 'in_service',
    rigId: 'AD-202',
    rigName: 'Rig Bravo',
    location: 'Well ADB-52 — Generator House',
    manufacturer: 'Caterpillar',
    model: '3516C',
    serialNumber: 'CAT-3516C-2020-ADI01',
    purchaseDate: '2020-05-01',
    purchaseCost: 780000,
    currentValue: 560000,
    expectedLifeYears: 20,
    ageYears: 5,
    serviceHours: 28400,
    lastInspectionDate: '2025-11-10',
    nextInspectionDate: '2026-05-10',
    lastPMDate: '2025-11-10',
    nextPMDate: '2026-02-10',
    specifications: [
      { key: 'Power Output (prime)', value: '2,000', unit: 'kW' },
      { key: 'Fuel Type', value: 'Diesel', unit: '' },
      { key: 'Alternator Voltage', value: '480V / 3-phase / 60Hz', unit: '' },
    ],
    certificates: [],
    inspectionHistory: [],
    maintenanceHistory: [],
    associatedNcoIds: [],
    associatedMocIds: [],
    tags: ['Generator', 'Power Generation', 'Caterpillar 3516C', 'Rig Bravo'],
  },

  // ── RIG CHARLIE (AD-203) ──────────────────────────────────────────
  {
    id: 'AD-203-BOP-001',
    assetTag: 'AD-203-BOP-001',
    description: 'Shaffer 13-5/8" 10,000 PSI 4-Ram BOP Stack',
    category: 'well_control',
    status: 'in_service',
    rigId: 'AD-203',
    rigName: 'Rig Charlie',
    location: 'Well ADB-61 — Wellhead',
    manufacturer: 'National Oilwell Varco (Shaffer)',
    model: 'Shaffer Type SL',
    serialNumber: 'SHF-SL-2021-0089',
    purchaseDate: '2021-09-01',
    purchaseCost: 2950000,
    currentValue: 2500000,
    expectedLifeYears: 25,
    ageYears: 4,
    lastInspectionDate: '2025-09-01',
    nextInspectionDate: '2027-09-01',
    lastPMDate: '2025-09-01',
    nextPMDate: '2026-03-01',
    certificationExpiryDate: '2027-09-30',
    specifications: [
      { key: 'Bore Size', value: '13-5/8', unit: 'inches' },
      { key: 'Working Pressure', value: '10,000', unit: 'PSI' },
      { key: 'Ram Configuration', value: 'Pipe / Blind-Shear / Pipe / Variable Bore', unit: '' },
      { key: 'API Standard', value: 'API 16A 3rd Edition', unit: '' },
    ],
    certificates: [],
    inspectionHistory: [],
    maintenanceHistory: [],
    associatedNcoIds: [],
    associatedMocIds: [],
    tags: ['BOP', 'Well Control', 'Shaffer', 'Critical Equipment', 'Rig Charlie'],
  },
  {
    id: 'AD-203-GEN-001',
    assetTag: 'AD-203-GEN-001',
    description: 'Caterpillar 3516B Main Generator Set #1 — 1,800 kW',
    category: 'power_generation',
    status: 'in_service',
    rigId: 'AD-203',
    rigName: 'Rig Charlie',
    location: 'Well ADB-61 — Generator House',
    manufacturer: 'Caterpillar',
    model: '3516B',
    serialNumber: 'CAT-3516B-2021-ADI03A',
    purchaseDate: '2021-09-01',
    purchaseCost: 680000,
    currentValue: 540000,
    expectedLifeYears: 20,
    ageYears: 4,
    serviceHours: 12800,
    lastInspectionDate: '2025-09-01',
    nextInspectionDate: '2026-03-01',
    lastPMDate: '2025-09-01',
    nextPMDate: '2026-03-01',
    specifications: [
      { key: 'Power Output (prime)', value: '1,800', unit: 'kW' },
      { key: 'Fuel Type', value: 'Diesel', unit: '' },
    ],
    certificates: [],
    inspectionHistory: [],
    maintenanceHistory: [],
    associatedNcoIds: [],
    associatedMocIds: [],
    tags: ['Generator', 'Power Generation', 'Caterpillar 3516B', 'Rig Charlie'],
  },
  {
    id: 'AD-203-GEN-002',
    assetTag: 'AD-203-GEN-002',
    description: 'Caterpillar 3516B Main Generator Set #2 — 1,800 kW',
    category: 'power_generation',
    status: 'maintenance',
    rigId: 'AD-203',
    rigName: 'Rig Charlie',
    location: 'Caterpillar Service Centre, Dammam (overhaul in progress)',
    manufacturer: 'Caterpillar',
    model: '3516B',
    serialNumber: 'CAT-3516B-2021-ADI03B',
    purchaseDate: '2021-09-01',
    purchaseCost: 680000,
    currentValue: 510000,
    expectedLifeYears: 20,
    ageYears: 4,
    serviceHours: 15400,
    lastInspectionDate: '2026-02-20',
    nextInspectionDate: '2026-08-20',
    lastPMDate: '2026-02-20',
    nextPMDate: '2026-09-01',
    specifications: [
      { key: 'Power Output (prime)', value: '1,800', unit: 'kW' },
      { key: 'Fuel Type', value: 'Diesel', unit: '' },
    ],
    certificates: [],
    inspectionHistory: [],
    maintenanceHistory: [],
    associatedNcoIds: [],
    associatedMocIds: ['MOC-2026-008'],
    tags: ['Generator', 'Power Generation', 'Caterpillar 3516B', 'Rig Charlie', 'Out of Service'],
    notes: 'MOC-2026-008: generator undergoing major overhaul at CAT Dammam. Temporary rental unit on-site.',
  },
  {
    id: 'AD-203-SHA-001',
    assetTag: 'AD-203-SHA-001',
    description: 'Derrick FLC 500 Shale Shaker #1',
    category: 'circulating',
    status: 'in_service',
    rigId: 'AD-203',
    rigName: 'Rig Charlie',
    location: 'Well ADB-61 — Shaker House',
    manufacturer: 'Derrick Equipment Company',
    model: 'FLC 500',
    serialNumber: 'DEC-FLC500-2021-AD203-01',
    purchaseDate: '2021-09-01',
    purchaseCost: 85000,
    currentValue: 65000,
    expectedLifeYears: 15,
    ageYears: 4,
    lastInspectionDate: '2025-12-01',
    nextInspectionDate: '2026-06-01',
    lastPMDate: '2025-12-01',
    nextPMDate: '2026-03-01',
    specifications: [
      { key: 'G-Force', value: '4.8', unit: 'G' },
      { key: 'Motion Type', value: 'Linear', unit: '' },
      { key: 'Screen Area', value: '2.97', unit: 'm²' },
    ],
    certificates: [],
    inspectionHistory: [],
    maintenanceHistory: [],
    associatedNcoIds: [],
    associatedMocIds: ['MOC-2026-010'],
    tags: ['Shale Shaker', 'Solids Control', 'Derrick FLC 500', 'Rig Charlie', 'Upgrade Planned'],
    notes: 'MOC-2026-010 proposes upgrade to FLC 513 High-G units in April 2026.',
  },
  {
    id: 'AD-203-SHA-002',
    assetTag: 'AD-203-SHA-002',
    description: 'Derrick FLC 500 Shale Shaker #2',
    category: 'circulating',
    status: 'in_service',
    rigId: 'AD-203',
    rigName: 'Rig Charlie',
    location: 'Well ADB-61 — Shaker House',
    manufacturer: 'Derrick Equipment Company',
    model: 'FLC 500',
    serialNumber: 'DEC-FLC500-2021-AD203-02',
    purchaseDate: '2021-09-01',
    purchaseCost: 85000,
    currentValue: 65000,
    expectedLifeYears: 15,
    ageYears: 4,
    lastInspectionDate: '2025-12-01',
    nextInspectionDate: '2026-06-01',
    lastPMDate: '2025-12-01',
    nextPMDate: '2026-03-01',
    specifications: [
      { key: 'G-Force', value: '4.8', unit: 'G' },
      { key: 'Motion Type', value: 'Linear', unit: '' },
    ],
    certificates: [],
    inspectionHistory: [],
    maintenanceHistory: [],
    associatedNcoIds: [],
    associatedMocIds: ['MOC-2026-010'],
    tags: ['Shale Shaker', 'Solids Control', 'Derrick FLC 500', 'Rig Charlie'],
  },
  {
    id: 'AD-203-SHA-003',
    assetTag: 'AD-203-SHA-003',
    description: 'Derrick FLC 500 Shale Shaker #3',
    category: 'circulating',
    status: 'in_service',
    rigId: 'AD-203',
    rigName: 'Rig Charlie',
    location: 'Well ADB-61 — Shaker House',
    manufacturer: 'Derrick Equipment Company',
    model: 'FLC 500',
    serialNumber: 'DEC-FLC500-2021-AD203-03',
    purchaseDate: '2021-09-01',
    purchaseCost: 85000,
    currentValue: 65000,
    expectedLifeYears: 15,
    ageYears: 4,
    lastInspectionDate: '2025-12-01',
    nextInspectionDate: '2026-06-01',
    lastPMDate: '2025-12-01',
    nextPMDate: '2026-03-01',
    specifications: [],
    certificates: [],
    inspectionHistory: [],
    maintenanceHistory: [],
    associatedNcoIds: [],
    associatedMocIds: ['MOC-2026-010'],
    tags: ['Shale Shaker', 'Solids Control', 'Rig Charlie'],
  },
  {
    id: 'AD-203-SHA-004',
    assetTag: 'AD-203-SHA-004',
    description: 'Derrick FLC 500 Shale Shaker #4',
    category: 'circulating',
    status: 'in_service',
    rigId: 'AD-203',
    rigName: 'Rig Charlie',
    location: 'Well ADB-61 — Shaker House',
    manufacturer: 'Derrick Equipment Company',
    model: 'FLC 500',
    serialNumber: 'DEC-FLC500-2021-AD203-04',
    purchaseDate: '2021-09-01',
    purchaseCost: 85000,
    currentValue: 65000,
    expectedLifeYears: 15,
    ageYears: 4,
    lastInspectionDate: '2025-12-01',
    nextInspectionDate: '2026-06-01',
    lastPMDate: '2025-12-01',
    nextPMDate: '2026-03-01',
    specifications: [],
    certificates: [],
    inspectionHistory: [],
    maintenanceHistory: [],
    associatedNcoIds: [],
    associatedMocIds: ['MOC-2026-010'],
    tags: ['Shale Shaker', 'Solids Control', 'Rig Charlie'],
  },
  {
    id: 'AD-203-TDS-001',
    assetTag: 'AD-203-TDS-001',
    description: 'Varco TDS-9SA Top Drive System',
    category: 'rotating',
    status: 'in_service',
    rigId: 'AD-203',
    rigName: 'Rig Charlie',
    location: 'Well ADB-61 — Derrick',
    manufacturer: 'National Oilwell Varco',
    model: 'TDS-9SA',
    serialNumber: 'NOV-TDS9SA-2021-0312',
    purchaseDate: '2021-09-01',
    purchaseCost: 1450000,
    currentValue: 1200000,
    expectedLifeYears: 20,
    ageYears: 4,
    serviceHours: 7800,
    lastInspectionDate: '2025-09-01',
    nextInspectionDate: '2026-03-01',
    lastPMDate: '2025-12-01',
    nextPMDate: '2026-03-01',
    specifications: [
      { key: 'Rating', value: '400', unit: 'ton' },
      { key: 'Motor HP', value: '1,000', unit: 'HP' },
      { key: 'Max Torque', value: '30,000', unit: 'ft-lb' },
    ],
    certificates: [],
    inspectionHistory: [],
    maintenanceHistory: [],
    associatedNcoIds: [],
    associatedMocIds: [],
    tags: ['Top Drive', 'NOV', 'Rotating Equipment', 'Rig Charlie'],
  },

  // ── BASE / FLEET ASSETS ────────────────────────────────────────────
  {
    id: 'ADI-SAMP-001',
    assetTag: 'ADI-SAMP-001',
    description: 'Thread Gauge Set — API NC50 / 6-5/8" IF — Rig Alpha',
    category: 'instrumentation',
    status: 'in_service',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    location: 'Well ADB-47 — Quality Lab Container',
    manufacturer: 'Ott Jakob / API Standard',
    model: 'Ring & Plug Gauge Set — API NC-50',
    serialNumber: 'ADI-GAUGE-AD201-001',
    purchaseDate: '2020-03-15',
    purchaseCost: 18500,
    currentValue: 12000,
    expectedLifeYears: 10,
    ageYears: 5,
    lastInspectionDate: '2025-11-15',
    nextInspectionDate: '2026-05-15',
    lastPMDate: '2025-11-15',
    nextPMDate: '2026-05-15',
    specifications: [
      { key: 'Thread Form', value: 'API NC-50 (6-5/8" IF)', unit: '' },
      { key: 'Calibration Standard', value: 'API RP 7G-2', unit: '' },
      { key: 'Calibration Interval', value: '6 months', unit: '' },
    ],
    certificates: [
      {
        id: 'CERT-GAUGE001-001',
        type: 'Calibration Certificate — API Thread Gauges',
        issuedBy: 'National Measurement Institute (Accredited)',
        issuedDate: '2025-11-15',
        expiryDate: '2026-05-15',
        certificateNumber: 'CAL-2025-AD201-GAUGE-001',
        status: 'valid',
      },
    ],
    inspectionHistory: [
      {
        id: 'INSP-GAUGE001-001',
        date: '2025-11-15',
        type: 'Semi-Annual Calibration',
        inspectedBy: 'TÜV Rheinland Calibration Lab',
        result: 'pass',
        findings: 'Both NC-50 ring gauge and 6-5/8" IF ring gauge within calibration tolerance per API RP 7G-2 after being replaced/recalibrated following NCO-2025-007.',
        nextInspectionDate: '2026-05-15',
        reportRef: 'Cal-Lab-Report-ThreadGauge-AD201-Nov2025.pdf',
      },
    ],
    maintenanceHistory: [],
    associatedNcoIds: ['NCO-2025-007'],
    associatedMocIds: [],
    tags: ['Thread Gauge', 'Calibration', 'Quality', 'API NC-50', 'Rig Alpha'],
  },
];

export const getAssetById = (id: string): Asset | undefined =>
  ASSETS.find((a) => a.id === id);

export const getAssetsByRig = (rigId: string): Asset[] =>
  ASSETS.filter((a) => a.rigId === rigId);

export const getAssetsByCategory = (category: AssetCategory): Asset[] =>
  ASSETS.filter((a) => a.category === category);

export const getAssetsByStatus = (status: AssetStatus): Asset[] =>
  ASSETS.filter((a) => a.status === status);
