// ============================================================
// HR ACTIVITIES — DUMMY DATA
// Oil & Gas Operations Management Platform — ADI
// ============================================================

import type { LeaveRequest, HrAction } from '@/lib/types/index';

export const LEAVE_REQUESTS: LeaveRequest[] = [
  {
    id: 'LVR-001',
    employeeId: 'ADI-EMP-0045',
    employeeName: 'Omar Hassan',
    leaveType: 'annual',
    startDate: '2026-03-15',
    endDate: '2026-03-28',
    days: 14,
    reason: 'Family vacation and personal commitments.',
    status: 'approved',
    approvedBy: 'James Cooper',
    submittedDate: '2026-02-20',
    rigId: 'AD-201',
  },
  {
    id: 'LVR-002',
    employeeId: 'ADI-EMP-0062',
    employeeName: 'Mohammed Al-Dosari',
    leaveType: 'sick',
    startDate: '2026-03-01',
    endDate: '2026-03-05',
    days: 5,
    reason: 'Medical treatment — knee procedure, doctor recommendation.',
    status: 'approved',
    approvedBy: 'James Cooper',
    submittedDate: '2026-02-26',
    rigId: 'AD-201',
  },
  {
    id: 'LVR-003',
    employeeId: 'ADI-EMP-0071',
    employeeName: 'Ali Hassan',
    leaveType: 'emergency',
    startDate: '2026-02-28',
    endDate: '2026-03-04',
    days: 5,
    reason: 'Father hospitalised — emergency family situation.',
    status: 'pending',
    approvedBy: null,
    submittedDate: '2026-02-27',
    rigId: 'AD-201',
  },
  {
    id: 'LVR-004',
    employeeId: 'ADI-EMP-0053',
    employeeName: 'Emma Richards',
    leaveType: 'annual',
    startDate: '2026-04-01',
    endDate: '2026-04-14',
    days: 14,
    reason: 'Planned annual leave — rotation break.',
    status: 'pending',
    approvedBy: null,
    submittedDate: '2026-02-25',
    rigId: 'AD-201',
  },
  {
    id: 'LVR-005',
    employeeId: 'ADI-EMP-0028',
    employeeName: 'Khalid Mahmoud',
    leaveType: 'compassionate',
    startDate: '2026-03-08',
    endDate: '2026-03-12',
    days: 5,
    reason: 'Bereavement — passing of father-in-law.',
    status: 'approved',
    approvedBy: 'James Cooper',
    submittedDate: '2026-03-07',
    rigId: 'AD-201',
  },
  {
    id: 'LVR-006',
    employeeId: 'ADI-EMP-0039',
    employeeName: 'Carlos Mendez',
    leaveType: 'annual',
    startDate: '2026-03-20',
    endDate: '2026-04-02',
    days: 14,
    reason: 'Scheduled rotation leave.',
    status: 'approved',
    approvedBy: 'James Cooper',
    submittedDate: '2026-02-15',
    rigId: 'AD-202',
  },
  {
    id: 'LVR-007',
    employeeId: 'ADI-EMP-0077',
    employeeName: 'Peter Okafor',
    leaveType: 'unpaid',
    startDate: '2026-04-10',
    endDate: '2026-04-20',
    days: 11,
    reason: 'Personal travel — attending professional conference.',
    status: 'rejected',
    approvedBy: null,
    submittedDate: '2026-02-18',
    rigId: 'AD-203',
  },
  {
    id: 'LVR-008',
    employeeId: 'ADI-EMP-0058',
    employeeName: 'Nadia Petrova',
    leaveType: 'sick',
    startDate: '2026-02-24',
    endDate: '2026-02-26',
    days: 3,
    reason: 'Influenza — confined to quarters per rig medic instruction.',
    status: 'approved',
    approvedBy: 'Carlos Mendez',
    submittedDate: '2026-02-24',
    rigId: 'AD-202',
  },
];

export const HR_ACTIONS: HrAction[] = [
  {
    id: 'HRA-001',
    employeeId: 'ADI-EMP-0045',
    employeeName: 'Omar Hassan',
    actionType: 'promotion',
    effectiveDate: '2026-04-01',
    description: 'Promoted from Senior Driller to Rig Manager following outstanding performance review and 5 years of service.',
    fromPosition: 'Senior Driller',
    toPosition: 'Rig Manager',
    status: 'approved',
    initiatedBy: 'James Cooper',
    initiatedDate: '2026-02-15',
    rigId: 'AD-201',
  },
  {
    id: 'HRA-002',
    employeeId: 'ADI-EMP-0062',
    employeeName: 'Mohammed Al-Dosari',
    actionType: 'transfer',
    effectiveDate: '2026-04-15',
    description: 'Transfer from Rig Alpha to Rig Bravo to support increased drilling activity and backfill vacancy.',
    fromPosition: 'Well Control Specialist / Senior Driller — Rig Alpha',
    toPosition: 'Well Control Specialist / Senior Driller — Rig Bravo',
    status: 'pending',
    initiatedBy: 'James Cooper',
    initiatedDate: '2026-02-20',
    rigId: 'AD-201',
  },
  {
    id: 'HRA-003',
    employeeId: 'ADI-EMP-0083',
    employeeName: 'Sami Al-Otaibi',
    actionType: 'warning',
    effectiveDate: '2026-02-22',
    description: 'Written warning issued for repeated failure to submit daily maintenance logs within agreed timeframe. Third offence in 60 days.',
    fromPosition: 'Mechanical Supervisor',
    toPosition: 'Mechanical Supervisor',
    status: 'completed',
    initiatedBy: 'Tom Bradshaw',
    initiatedDate: '2026-02-21',
    rigId: 'AD-203',
  },
  {
    id: 'HRA-004',
    employeeId: 'ADI-EMP-0059',
    employeeName: 'Sarah Mitchell',
    actionType: 'promotion',
    effectiveDate: '2026-03-01',
    description: 'Promoted to Quality Manager following ISO re-certification audit lead role and two years of exemplary performance.',
    fromPosition: 'Quality Engineer',
    toPosition: 'Quality Manager',
    status: 'completed',
    initiatedBy: 'Hassan Al-Qahtani',
    initiatedDate: '2026-02-10',
    rigId: 'AD-203',
  },
  {
    id: 'HRA-005',
    employeeId: 'ADI-EMP-0091',
    employeeName: 'Yusuf Ibrahim',
    actionType: 'demotion',
    effectiveDate: '2026-03-10',
    description: 'Demotion from Warehouse Supervisor to Senior Warehouse Operative following inventory control audit findings and confirmed procedural violations.',
    fromPosition: 'Warehouse Supervisor',
    toPosition: 'Senior Warehouse Operative',
    status: 'pending',
    initiatedBy: 'Khalid Al-Harbi',
    initiatedDate: '2026-02-25',
    rigId: 'AD-201',
  },
];
