// =============================================================================
// HSE DUMMY DATA — Training Records & HSE Events
// Oil & Gas Operations Management Platform — ADI
// =============================================================================

import type { TrainingRecord, HseEvent } from '@/lib/types/index';

// ─── Training Records ─────────────────────────────────────────────────────────

export const TRAINING_RECORDS: TrainingRecord[] = [
  {
    id: 'TRN-001',
    personnelId: 'usr-emp-001',
    personnelName: 'Ahmed Al-Rashid',
    trainingName: 'IWCF Well Control - Supervisor Level',
    provider: 'IWCF Aberdeen',
    completedDate: '2024-03-15',
    expiryDate: '2026-03-15',
    status: 'expiring',
    certificateNumber: 'IWCF-2024-S-44821',
    department: 'rig_operations',
    rigId: 'AD-201',
  },
  {
    id: 'TRN-002',
    personnelId: 'usr-rm-001',
    personnelName: 'Emma Richards',
    trainingName: 'NEBOSH IGC - International General Certificate',
    provider: 'NEBOSH UK',
    completedDate: '2023-06-20',
    expiryDate: '2026-06-20',
    status: 'valid',
    certificateNumber: 'NEBOSH-IGC-2023-78954',
    department: 'rig_operations',
    rigId: 'AD-201',
  },
  {
    id: 'TRN-003',
    personnelId: 'usr-emp-002',
    personnelName: 'James Okonkwo',
    trainingName: 'OPITO BOSIET - Basic Offshore Safety Induction & Emergency Training',
    provider: 'OPITO Approved Centre - Abu Dhabi',
    completedDate: '2022-09-10',
    expiryDate: '2025-09-10',
    status: 'expired',
    certificateNumber: 'OPITO-BOSIET-2022-33017',
    department: 'rig_operations',
    rigId: 'AD-201',
  },
  {
    id: 'TRN-004',
    personnelId: 'usr-emp-003',
    personnelName: 'Mohammed Al-Dosari',
    trainingName: 'IWCF Well Control - Driller Level',
    provider: 'IWCF Houston',
    completedDate: '2024-11-05',
    expiryDate: '2026-11-05',
    status: 'valid',
    certificateNumber: 'IWCF-2024-D-51203',
    department: 'rig_operations',
    rigId: 'AD-201',
  },
  {
    id: 'TRN-005',
    personnelId: 'usr-emp-004',
    personnelName: 'Ricardo Santos',
    trainingName: 'H2S Alive - Hydrogen Sulphide Safety',
    provider: 'Energy Safety Canada',
    completedDate: '2023-04-18',
    expiryDate: '2025-04-18',
    status: 'expired',
    certificateNumber: 'H2SALIVE-2023-CA-8841',
    department: 'rig_operations',
    rigId: 'AD-201',
  },
  {
    id: 'TRN-006',
    personnelId: 'usr-emp-005',
    personnelName: 'Khalid Mahmoud',
    trainingName: 'Confined Space Entry & Rescue',
    provider: 'Arabian Safety Institute',
    completedDate: '2024-07-22',
    expiryDate: '2026-07-22',
    status: 'valid',
    certificateNumber: 'ASI-CSE-2024-0714',
    department: 'rig_operations',
    rigId: 'AD-201',
  },
  {
    id: 'TRN-007',
    personnelId: 'usr-emp-006',
    personnelName: 'Ali Hassan',
    trainingName: 'Working at Height - Advanced Rescue',
    provider: 'IRATA International',
    completedDate: '2024-01-30',
    expiryDate: '2026-02-01',
    status: 'expiring',
    certificateNumber: 'IRATA-WAH-2024-L2-92011',
    department: 'rig_operations',
    rigId: 'AD-201',
  },
  {
    id: 'TRN-008',
    personnelId: 'usr-emp-007',
    personnelName: 'Omar Hassan',
    trainingName: 'Rigging & Lifting Operations - Supervisor',
    provider: 'Lifting Equipment Engineers Association',
    completedDate: '2023-10-12',
    expiryDate: '2026-10-12',
    status: 'valid',
    certificateNumber: 'LEEA-RLS-2023-44520',
    department: 'rig_operations',
    rigId: 'AD-201',
  },
  {
    id: 'TRN-009',
    personnelId: 'usr-emp-008',
    personnelName: 'Jack Anderson',
    trainingName: 'Offshore Fire Fighting - Advanced',
    provider: 'OPITO Approved Centre - Dubai',
    completedDate: '2023-08-05',
    expiryDate: '2025-08-05',
    status: 'expired',
    certificateNumber: 'OPITO-FF-2023-ADV-18842',
    department: 'rig_operations',
    rigId: 'AD-201',
  },
  {
    id: 'TRN-010',
    personnelId: 'usr-emp-009',
    personnelName: 'Fatima Al-Zaabi',
    trainingName: 'HAZMAT - Hazardous Materials Handling',
    provider: 'NEBOSH UK',
    completedDate: '2024-05-14',
    expiryDate: '2026-05-14',
    status: 'valid',
    certificateNumber: 'NEBOSH-HAZMAT-2024-62391',
    department: 'rig_operations',
    rigId: 'AD-201',
  },
  {
    id: 'TRN-011',
    personnelId: 'usr-emp-010',
    personnelName: 'Lars Petersen',
    trainingName: 'ISO 9001 Lead Auditor',
    provider: 'Bureau Veritas Academy',
    completedDate: '2023-02-28',
    expiryDate: '2026-02-28',
    status: 'expiring',
    certificateNumber: 'BV-ISO9001-LA-2023-7741',
    department: 'rig_operations',
    rigId: 'AD-201',
  },
  {
    id: 'TRN-012',
    personnelId: 'usr-emp-011',
    personnelName: 'David Osei',
    trainingName: 'OPITO HUET - Helicopter Underwater Escape Training',
    provider: 'OPITO Approved Centre - Aberdeen',
    completedDate: '2024-09-03',
    expiryDate: '2026-09-03',
    status: 'valid',
    certificateNumber: 'OPITO-HUET-2024-50932',
    department: 'rig_operations',
    rigId: 'AD-201',
  },
  {
    id: 'TRN-013',
    personnelId: 'usr-emp-012',
    personnelName: 'Youssef Benali',
    trainingName: 'First Aid & CPR - Offshore Level 3',
    provider: 'St John Ambulance International',
    completedDate: '2024-02-17',
    expiryDate: '2026-02-17',
    status: 'expiring',
    certificateNumber: 'SJA-FA3-2024-INT-30088',
    department: 'rig_operations',
    rigId: 'AD-201',
  },
  {
    id: 'TRN-014',
    personnelId: 'usr-emp-013',
    personnelName: 'Priya Nair',
    trainingName: 'H2S Alive - Hydrogen Sulphide Safety',
    provider: 'ASSE Middle East',
    completedDate: '2024-10-21',
    expiryDate: '2026-10-21',
    status: 'valid',
    certificateNumber: 'ASSE-H2S-2024-ME-77341',
    department: 'rig_operations',
    rigId: 'AD-201',
  },
  {
    id: 'TRN-015',
    personnelId: 'usr-emp-014',
    personnelName: 'Carlos Mendez',
    trainingName: 'Manual Handling & Ergonomics - Offshore',
    provider: 'Arabian Safety Institute',
    completedDate: '2022-06-11',
    expiryDate: '2025-06-11',
    status: 'expired',
    certificateNumber: 'ASI-MH-2022-0391',
    department: 'rig_operations',
    rigId: 'AD-201',
  },
];

// ─── HSE Events ────────────────────────────────────────────────────────────────

export const HSE_EVENTS: HseEvent[] = [
  {
    id: 'EVT-001',
    type: 'toolbox_talk',
    title: 'Daily Toolbox Talk - Lifting Operations Safety',
    date: '2026-02-28',
    time: '06:00',
    location: 'Rig Floor - Rig Alpha',
    conductor: 'James Okonkwo',
    attendeeCount: 18,
    notes: 'Covered safe lifting practices, sling inspection procedures, and load chart review for the 35T crane.',
    status: 'completed',
    rigId: 'AD-201',
  },
  {
    id: 'EVT-002',
    type: 'safety_meeting',
    title: 'Weekly HSE Committee Meeting - February Week 4',
    date: '2026-02-27',
    time: '09:00',
    location: 'Conference Room - Rig Alpha',
    conductor: 'Emma Richards',
    attendeeCount: 12,
    notes: 'Reviewed open stop cards and near miss status. Discussed upcoming H2S drill schedule. Agreed actions for overdue audit findings.',
    status: 'completed',
    rigId: 'AD-201',
  },
  {
    id: 'EVT-003',
    type: 'drill',
    title: 'H2S Emergency Drill - Full Muster & Escape',
    date: '2026-02-26',
    time: '14:00',
    location: 'Rig Alpha - All Decks',
    conductor: 'Ali Hassan',
    attendeeCount: 67,
    notes: 'Full rig muster drill with H2S alarm simulation. Muster time: 6 min 42 sec — within 7-minute target. All personnel accounted for.',
    status: 'completed',
    rigId: 'AD-201',
  },
  {
    id: 'EVT-004',
    type: 'inspection',
    title: 'Monthly Fire & Gas System Inspection',
    date: '2026-02-25',
    time: '08:00',
    location: 'All Areas - Rig Alpha',
    conductor: 'Khalid Mahmoud',
    attendeeCount: 3,
    notes: 'All fire detectors tested and confirmed operational. 2 gas detector heads flagged for calibration — raised as maintenance work orders.',
    status: 'completed',
    rigId: 'AD-201',
  },
  {
    id: 'EVT-005',
    type: 'toolbox_talk',
    title: 'Toolbox Talk - Working in Confined Spaces',
    date: '2026-02-24',
    time: '06:30',
    location: 'Mud Pit Area',
    conductor: 'James Okonkwo',
    attendeeCount: 9,
    notes: 'Reviewed confined space entry permit requirements, atmosphere testing procedures, and standby man responsibilities.',
    status: 'completed',
    rigId: 'AD-201',
  },
  {
    id: 'EVT-006',
    type: 'training_session',
    title: 'Dropped Object Prevention & DROPS Calculator Training',
    date: '2026-02-23',
    time: '10:00',
    location: 'Training Room - Rig Alpha',
    conductor: 'Ali Hassan',
    attendeeCount: 22,
    notes: 'Full DROPS awareness session following NM-2026-001 dropped object incident. All derrick and height workers in attendance.',
    status: 'completed',
    rigId: 'AD-201',
  },
  {
    id: 'EVT-007',
    type: 'drill',
    title: 'Well Control Drill - BOP Shut-in Procedure',
    date: '2026-02-22',
    time: '07:00',
    location: 'Wellhead / Drill Floor - Rig Alpha',
    conductor: 'Mohammed Al-Dosari',
    attendeeCount: 14,
    notes: 'Kick detection and shut-in drill. Response time: 2 min 08 sec. All crew performed correctly. Follow-up drill scheduled for 14-day cycle.',
    status: 'completed',
    rigId: 'AD-201',
  },
  {
    id: 'EVT-008',
    type: 'safety_meeting',
    title: 'HSE Leadership Walkthrough - Rig Manager & Client Rep',
    date: '2026-02-21',
    time: '10:30',
    location: 'Rig Alpha - Full Rig Tour',
    conductor: 'Emma Richards',
    attendeeCount: 4,
    notes: 'Monthly leadership walkthrough. 3 positive observations noted. 1 unsafe condition raised (loose grating — SC-2026-001 raised as result).',
    status: 'completed',
    rigId: 'AD-201',
  },
  {
    id: 'EVT-009',
    type: 'toolbox_talk',
    title: 'Toolbox Talk - Manual Handling & Back Injury Prevention',
    date: '2026-03-03',
    time: '06:00',
    location: 'Drill Floor - Rig Alpha',
    conductor: 'James Okonkwo',
    attendeeCount: 16,
    notes: 'Scheduled session covering correct manual handling techniques for tubular handling operations.',
    status: 'scheduled',
    rigId: 'AD-201',
  },
  {
    id: 'EVT-010',
    type: 'drill',
    title: 'Fire Drill - Engine Room & Accommodation Block',
    date: '2026-03-05',
    time: '13:00',
    location: 'Power House & Accommodation - Rig Alpha',
    conductor: 'Ali Hassan',
    attendeeCount: 0,
    notes: 'Bi-monthly fire response drill. Focus on engine room scenario. Emergency response team to participate with full SCBA.',
    status: 'scheduled',
    rigId: 'AD-201',
  },
  {
    id: 'EVT-011',
    type: 'training_session',
    title: 'PTW System Refresher Training - Permit to Work',
    date: '2026-03-07',
    time: '09:00',
    location: 'Training Room - Rig Alpha',
    conductor: 'Emma Richards',
    attendeeCount: 0,
    notes: 'Mandatory refresher following audit finding AI-2026-008. All PTW issuers and receivers to attend. SIMOPS certificate holders priority.',
    status: 'scheduled',
    rigId: 'AD-201',
  },
  {
    id: 'EVT-012',
    type: 'inspection',
    title: 'Quarterly Lifesaving Equipment Inspection',
    date: '2026-02-15',
    time: '08:00',
    location: 'Muster Stations & Lifeboat Deck - Rig Alpha',
    conductor: 'Khalid Mahmoud',
    attendeeCount: 4,
    notes: 'Quarterly inspection cancelled due to crane maintenance blocking lifeboat deck access. Rescheduled to 2026-03-10.',
    status: 'cancelled',
    rigId: 'AD-201',
  },
];
