// ============================================================
// MATERIAL ALLOCATIONS DUMMY DATA
// Oil & Gas Operations Management Platform — ADI
// ============================================================

import type { MaterialAllocation } from '@/lib/types/index';

export const MATERIAL_ALLOCATIONS: MaterialAllocation[] = [
  {
    id: 'ALLOC-001',
    itemId: 'WH-PPE-001',
    itemName: 'Safety Helmet — MSA V-Gard, White (Supervisors)',
    partNumber: 'ADI-PPE-HELM-001',
    allocatedToId: 'usr-emp-001',
    allocatedToName: 'Ahmed Al-Rashid',
    quantity: 1,
    unit: 'each',
    allocatedDate: '2026-01-15',
    returnDate: null,
    status: 'active',
    notes: 'White helmet — Driller designation',
  },
  {
    id: 'ALLOC-002',
    itemId: 'WH-PPE-006',
    itemName: 'H2S/LEL/CO Personal Gas Monitor — MSA Altair 5X',
    partNumber: 'ADI-PPE-H2S-001',
    allocatedToId: 'usr-emp-001',
    allocatedToName: 'Ahmed Al-Rashid',
    quantity: 1,
    unit: 'each',
    allocatedDate: '2026-01-15',
    returnDate: null,
    status: 'active',
    notes: 'Unit serial #ALT-4421 — calibrated 2026-01-10',
  },
  {
    id: 'ALLOC-003',
    itemId: 'WH-PPE-001',
    itemName: 'Safety Helmet — MSA V-Gard, White (Supervisors)',
    partNumber: 'ADI-PPE-HELM-001',
    allocatedToId: 'usr-emp-002',
    allocatedToName: 'Emma Richards',
    quantity: 1,
    unit: 'each',
    allocatedDate: '2026-01-20',
    returnDate: null,
    status: 'active',
    notes: 'HSE Manager — white helmet with HSE sticker',
  },
  {
    id: 'ALLOC-004',
    itemId: 'WH-PPE-003',
    itemName: 'Safety Boots — Blundstone 990, Steel Toe & Midsole',
    partNumber: 'ADI-PPE-BOOT-001',
    allocatedToId: 'usr-emp-002',
    allocatedToName: 'Emma Richards',
    quantity: 1,
    unit: 'pair',
    allocatedDate: '2026-01-20',
    returnDate: null,
    status: 'active',
    notes: 'UK Size 6',
  },
  {
    id: 'ALLOC-005',
    itemId: 'WH-TOOL-002',
    itemName: 'Breakout Tong — B.J. Operations 10" HWDP',
    partNumber: 'ADI-TOOL-BREAKOUTTONS-001',
    allocatedToId: 'usr-emp-003',
    allocatedToName: 'Khalid Al-Zahrani',
    quantity: 1,
    unit: 'each',
    allocatedDate: '2026-02-01',
    returnDate: null,
    status: 'active',
    notes: 'Assigned to Drill Floor crew — tagged KAZ-01',
  },
  {
    id: 'ALLOC-006',
    itemId: 'WH-PPE-004',
    itemName: 'Mechanic Gloves — Ansell Heavy Duty Mechanical, Size L',
    partNumber: 'ADI-PPE-GLOVE-001',
    allocatedToId: 'usr-emp-003',
    allocatedToName: 'Khalid Al-Zahrani',
    quantity: 3,
    unit: 'pair',
    allocatedDate: '2026-02-01',
    returnDate: null,
    status: 'active',
    notes: 'Monthly allocation — replace as consumed',
  },
  {
    id: 'ALLOC-007',
    itemId: 'WH-PPE-006',
    itemName: 'H2S/LEL/CO Personal Gas Monitor — MSA Altair 5X',
    partNumber: 'ADI-PPE-H2S-001',
    allocatedToId: 'usr-emp-004',
    allocatedToName: 'James Okafor',
    quantity: 1,
    unit: 'each',
    allocatedDate: '2026-01-28',
    returnDate: null,
    status: 'active',
    notes: 'Unit serial #ALT-4488 — night shift',
  },
  {
    id: 'ALLOC-008',
    itemId: 'WH-PPE-007',
    itemName: 'Self-Contained Breathing Apparatus (SCBA) — MSA AX2100',
    partNumber: 'ADI-PPE-SCBA-001',
    allocatedToId: 'usr-emp-005',
    allocatedToName: 'Fatima Al-Otaibi',
    quantity: 1,
    unit: 'set',
    allocatedDate: '2026-02-05',
    returnDate: null,
    status: 'active',
    notes: 'Emergency Response Team — SCBA team leader',
  },
  {
    id: 'ALLOC-009',
    itemId: 'WH-TOOL-003',
    itemName: 'Hydraulic Torque Wrench — Enerpac HMT-Series, 1,200 ft-lb',
    partNumber: 'ADI-TOOL-TORQUEWRENCH-001',
    allocatedToId: 'usr-emp-006',
    allocatedToName: 'Marco Pellegrini',
    quantity: 1,
    unit: 'set',
    allocatedDate: '2026-02-10',
    returnDate: null,
    status: 'active',
    notes: 'Maintenance department — BOP flange work',
  },
  {
    id: 'ALLOC-010',
    itemId: 'WH-PPE-002',
    itemName: 'Safety Helmet — MSA V-Gard, Yellow (Workers)',
    partNumber: 'ADI-PPE-HELM-002',
    allocatedToId: 'usr-emp-007',
    allocatedToName: 'Saud Al-Mutairi',
    quantity: 1,
    unit: 'each',
    allocatedDate: '2026-02-12',
    returnDate: null,
    status: 'active',
    notes: 'New crew rotation — derrickman',
  },
  {
    id: 'ALLOC-011',
    itemId: 'WH-PPE-003',
    itemName: 'Safety Boots — Blundstone 990, Steel Toe & Midsole',
    partNumber: 'ADI-PPE-BOOT-001',
    allocatedToId: 'usr-emp-007',
    allocatedToName: 'Saud Al-Mutairi',
    quantity: 1,
    unit: 'pair',
    allocatedDate: '2026-02-12',
    returnDate: '2026-02-20',
    status: 'returned',
    notes: 'Wrong size — UK 9 returned, UK 10 issued separately',
  },
  {
    id: 'ALLOC-012',
    itemId: 'WH-PPE-008',
    itemName: 'Chemical Splash Goggles — Honeywell Uvex Stealth',
    partNumber: 'ADI-PPE-GOGGLE-001',
    allocatedToId: 'usr-emp-008',
    allocatedToName: 'Ravi Shankar',
    quantity: 2,
    unit: 'each',
    allocatedDate: '2026-01-10',
    returnDate: '2026-02-08',
    status: 'returned',
    notes: 'Mud engineer — returned at end of hitch',
  },
  {
    id: 'ALLOC-013',
    itemId: 'WH-TOOL-001',
    itemName: 'Pipe Wrench — Ridgid 36" Heavy Duty',
    partNumber: 'ADI-TOOL-PWRENCH-001',
    allocatedToId: 'usr-emp-009',
    allocatedToName: 'Abdullah Hassan',
    quantity: 2,
    unit: 'each',
    allocatedDate: '2025-12-01',
    returnDate: null,
    status: 'lost',
    notes: 'Reported missing after rig floor cleanup — NCO raised',
  },
  {
    id: 'ALLOC-014',
    itemId: 'WH-PPE-006',
    itemName: 'H2S/LEL/CO Personal Gas Monitor — MSA Altair 5X',
    partNumber: 'ADI-PPE-H2S-001',
    allocatedToId: 'usr-emp-009',
    allocatedToName: 'Abdullah Hassan',
    quantity: 1,
    unit: 'each',
    allocatedDate: '2026-02-15',
    returnDate: null,
    status: 'active',
    notes: 'Replacement unit — serial #ALT-4512',
  },
  {
    id: 'ALLOC-015',
    itemId: 'WH-PPE-005',
    itemName: 'High Visibility Vest — 3M Class 2, Orange/Yellow',
    partNumber: 'ADI-PPE-VEST-HV-001',
    allocatedToId: 'usr-emp-010',
    allocatedToName: 'Carlos Rivera',
    quantity: 2,
    unit: 'each',
    allocatedDate: '2026-02-18',
    returnDate: null,
    status: 'active',
    notes: 'Logistics team — visitor escort requirement',
  },
];
