// ============================================================
// MATERIAL ORDERS DUMMY DATA
// Oil & Gas Operations Management Platform — ADI
// ============================================================

import type { MaterialOrder } from '@/lib/types/index';

export const MATERIAL_ORDERS: MaterialOrder[] = [
  {
    id: 'MO-001',
    orderNumber: 'PO-2026-0145',
    items: [
      {
        itemId: 'WH-MEC-003',
        itemName: 'Mud Pump Valve Assembly — National 12-P-160',
        partNumber: 'ADI-MEC-MUDPMPVLV-001',
        quantity: 6,
        unit: 'set',
        unitPrice: 2800,
      },
      {
        itemId: 'WH-MEC-001',
        itemName: 'Mud Pump Liner & Piston Assembly — National 12-P-160, 6.5"',
        partNumber: 'ADI-MEC-LINER-001',
        quantity: 3,
        unit: 'set',
        unitPrice: 4500,
      },
    ],
    requestedBy: 'Emma Richards',
    requestDate: '2026-02-20',
    status: 'ordered',
    supplier: 'National Oilwell Varco',
    expectedDelivery: '2026-03-10',
    totalAmount: 30300,
    notes: 'Urgently needed for scheduled mud pump overhaul on MDP-001',
    rigId: 'AD-201',
  },
  {
    id: 'MO-002',
    orderNumber: 'PO-2026-0138',
    items: [
      {
        itemId: 'WH-PPE-003',
        itemName: 'Safety Boots — Blundstone 990, Steel Toe & Midsole',
        partNumber: 'ADI-PPE-BOOT-001',
        quantity: 50,
        unit: 'pair',
        unitPrice: 420,
      },
      {
        itemId: 'WH-PPE-006',
        itemName: 'H2S/LEL/CO Personal Gas Monitor — MSA Altair 5X',
        partNumber: 'ADI-PPE-H2S-001',
        quantity: 10,
        unit: 'each',
        unitPrice: 2850,
      },
    ],
    requestedBy: 'Ahmed Al-Rashid',
    requestDate: '2026-02-15',
    status: 'approved',
    supplier: 'MSA Safety Arabia',
    expectedDelivery: '2026-03-05',
    totalAmount: 49500,
    notes: 'PPE stock replenishment — low stock items for Rig Alpha crew rotation',
    rigId: 'AD-201',
  },
  {
    id: 'MO-003',
    orderNumber: 'PO-2026-0122',
    items: [
      {
        itemId: 'WH-ELC-001',
        itemName: 'Variable Speed Drive (VSD) Module — ABB ACS880-37, 500 kW',
        partNumber: 'ADI-ELC-VARSPD-DRIVE-001',
        quantity: 1,
        unit: 'each',
        unitPrice: 185000,
      },
    ],
    requestedBy: 'Marco Pellegrini',
    requestDate: '2026-02-05',
    status: 'shipped',
    supplier: 'ABB Saudi Arabia',
    expectedDelivery: '2026-02-28',
    totalAmount: 185000,
    notes: 'Critical spare replacement — VSD unit damaged per NCO-2026-002. Air-freighted.',
    rigId: 'AD-201',
  },
  {
    id: 'MO-004',
    orderNumber: 'PO-2026-0109',
    items: [
      {
        itemId: 'WH-PPE-002',
        itemName: 'Safety Helmet — MSA V-Gard, Yellow (Workers)',
        partNumber: 'ADI-PPE-HELM-002',
        quantity: 200,
        unit: 'each',
        unitPrice: 58,
      },
      {
        itemId: 'WH-PPE-004',
        itemName: 'Mechanic Gloves — Ansell Heavy Duty Mechanical, Size L',
        partNumber: 'ADI-PPE-GLOVE-001',
        quantity: 300,
        unit: 'pair',
        unitPrice: 38,
      },
      {
        itemId: 'WH-PPE-005',
        itemName: 'High Visibility Vest — 3M Class 2, Orange/Yellow',
        partNumber: 'ADI-PPE-VEST-HV-001',
        quantity: 150,
        unit: 'each',
        unitPrice: 42,
      },
    ],
    requestedBy: 'Fatima Al-Otaibi',
    requestDate: '2026-01-28',
    status: 'received',
    supplier: 'Safety Supplies Arabia',
    expectedDelivery: '2026-02-10',
    totalAmount: 35700,
    notes: 'Quarterly PPE bulk order — all three rig sites. Received 2026-02-08.',
    rigId: 'AD-201',
  },
  {
    id: 'MO-005',
    orderNumber: 'PO-2026-0097',
    items: [
      {
        itemId: 'WH-MEC-005',
        itemName: 'Rotary Table Spherical Roller Bearing — SKF 23256 CACK/W33',
        partNumber: 'ADI-MEC-RTBBRG-001',
        quantity: 2,
        unit: 'each',
        unitPrice: 22000,
      },
    ],
    requestedBy: 'Khalid Al-Zahrani',
    requestDate: '2026-01-20',
    status: 'received',
    supplier: 'SKF Saudi Arabia',
    expectedDelivery: '2026-01-25',
    totalAmount: 44000,
    notes: 'Emergency reorder following MOC-2026-004. Fast-tracked delivery. Received 2026-01-24.',
    rigId: 'AD-201',
  },
  {
    id: 'MO-006',
    orderNumber: 'DRAFT-2026-016',
    items: [
      {
        itemId: 'WH-WCS-003',
        itemName: 'BOP Full Seal Kit — Shaffer 13-5/8" 10,000 PSI',
        partNumber: 'ADI-WCS-SEALKITBOP-001',
        quantity: 2,
        unit: 'set',
        unitPrice: 35000,
      },
      {
        itemId: 'WH-WCS-001',
        itemName: 'BOP Pipe Ram Block Assembly — Shaffer 13-5/8" 10,000 PSI',
        partNumber: 'ADI-WCS-RAMBLK-001',
        quantity: 1,
        unit: 'set',
        unitPrice: 48500,
      },
    ],
    requestedBy: 'Ahmed Al-Rashid',
    requestDate: '2026-02-26',
    status: 'draft',
    supplier: 'NOV Process & Flow Technologies',
    expectedDelivery: '2026-04-15',
    totalAmount: 118500,
    notes: 'Annual BOP spare parts replenishment — pending budget approval from RDM',
    rigId: 'AD-201',
  },
  {
    id: 'MO-007',
    orderNumber: 'PO-2026-0131',
    items: [
      {
        itemId: 'WH-MEC-007',
        itemName: 'Shale Shaker Screen — Derrick FLC 500, API 100 mesh',
        partNumber: 'ADI-MEC-SHAKER-SCREEN-001',
        quantity: 40,
        unit: 'each',
        unitPrice: 380,
      },
      {
        itemId: 'WH-CON-001',
        itemName: 'Gear Oil — ISO VG 220 (20 litre container)',
        partNumber: 'ADI-CON-GEAROIL-220-001',
        quantity: 20,
        unit: 'each',
        unitPrice: 320,
      },
    ],
    requestedBy: 'James Okafor',
    requestDate: '2026-02-10',
    status: 'submitted',
    supplier: 'Derrick Equipment ME',
    expectedDelivery: '2026-02-28',
    totalAmount: 21600,
    notes: 'Shale shaker screens for upcoming high-solids formation section',
    rigId: 'AD-201',
  },
  {
    id: 'MO-008',
    orderNumber: 'PO-2026-0085',
    items: [
      {
        itemId: 'WH-PPE-007',
        itemName: 'Self-Contained Breathing Apparatus (SCBA) — MSA AX2100',
        partNumber: 'ADI-PPE-SCBA-001',
        quantity: 6,
        unit: 'set',
        unitPrice: 9800,
      },
    ],
    requestedBy: 'Fatima Al-Otaibi',
    requestDate: '2026-01-15',
    status: 'received',
    supplier: 'MSA Safety Arabia',
    expectedDelivery: '2026-02-15',
    totalAmount: 58800,
    notes: 'SCBA fleet expansion — Emergency Response Team headcount increase. Received 2026-02-12.',
    rigId: 'AD-201',
  },
];
