// ============================================================
// ONBOARDING RECORDS — DUMMY DATA
// Oil & Gas Operations Management Platform — ADI
// ============================================================

import type { OnboardingRecord } from '@/lib/types/index';

export const ONBOARDING_RECORDS: OnboardingRecord[] = [
  {
    id: 'ONB-001',
    name: 'Mohammed Al-Farsi',
    company: 'ADI Drilling',
    role: 'Derrickman',
    nationality: 'Omani',
    passportNumber: 'AB1234567',
    emergencyContact: 'Fatima Al-Farsi',
    emergencyPhone: '+968-9876-5432',
    arrivalDate: '2026-02-25',
    status: 'checked_in',
    trainingTaskId: 'TSK-ONB-001',
    trainingStatus: 'completed',
    trainingAssignedTo: 'usr-hse-001',
    medicalTaskId: 'TSK-MED-001',
    medicalStatus: 'completed',
    medicalAssignedTo: 'usr-med-001',
    rigId: 'AD-201',
  },
  {
    id: 'ONB-002',
    name: 'Rajesh Kumar',
    company: 'Vendor Services Ltd',
    role: 'Cementing Engineer',
    nationality: 'Indian',
    passportNumber: 'J8765432',
    emergencyContact: 'Priya Kumar',
    emergencyPhone: '+91-98765-43210',
    arrivalDate: '2026-02-27',
    status: 'ready_for_checkin',
    trainingTaskId: 'TSK-ONB-003',
    trainingStatus: 'completed',
    trainingAssignedTo: 'usr-hse-001',
    medicalTaskId: 'TSK-MED-003',
    medicalStatus: 'completed',
    medicalAssignedTo: 'usr-med-001',
    rigId: 'AD-201',
  },
  {
    id: 'ONB-003',
    name: 'John Smith',
    company: 'Halliburton',
    role: 'MWD Engineer',
    nationality: 'American',
    passportNumber: 'US6543210',
    emergencyContact: 'Jane Smith',
    emergencyPhone: '+1-555-012-3456',
    arrivalDate: '2026-02-28',
    status: 'tasks_created',
    trainingTaskId: 'TSK-ONB-005',
    trainingStatus: 'pending',
    trainingAssignedTo: 'usr-hse-001',
    medicalTaskId: 'TSK-MED-005',
    medicalStatus: 'in_progress',
    medicalAssignedTo: 'usr-med-001',
    rigId: 'AD-201',
  },
  {
    id: 'ONB-004',
    name: 'Ali Al-Zahrani',
    company: 'ADI Drilling',
    role: 'Roughneck',
    nationality: 'Saudi',
    passportNumber: 'SA9876543',
    emergencyContact: 'Omar Al-Zahrani',
    emergencyPhone: '+966-55-876-5432',
    arrivalDate: '2026-02-28',
    status: 'info_submitted',
    trainingTaskId: null,
    trainingStatus: 'not_created',
    trainingAssignedTo: null,
    medicalTaskId: null,
    medicalStatus: 'not_created',
    medicalAssignedTo: null,
    rigId: 'AD-201',
  },
  {
    id: 'ONB-005',
    name: 'Pierre Dubois',
    company: 'Schlumberger',
    role: 'Wireline Engineer',
    nationality: 'French',
    passportNumber: 'FR1122334',
    emergencyContact: 'Marie Dubois',
    emergencyPhone: '+33-6-1234-5678',
    arrivalDate: '2026-03-01',
    status: 'pending_info',
    trainingTaskId: null,
    trainingStatus: 'not_created',
    trainingAssignedTo: null,
    medicalTaskId: null,
    medicalStatus: 'not_created',
    medicalAssignedTo: null,
    rigId: 'AD-201',
  },
  {
    id: 'ONB-006',
    name: 'Sung-Jin Park',
    company: 'Samsung Heavy Industries',
    role: 'Subsea Engineer',
    nationality: 'South Korean',
    passportNumber: 'KR5566778',
    emergencyContact: 'Ji-Young Park',
    emergencyPhone: '+82-10-5566-7788',
    arrivalDate: '2026-02-26',
    status: 'checked_in',
    trainingTaskId: 'TSK-ONB-002',
    trainingStatus: 'completed',
    trainingAssignedTo: 'usr-hse-001',
    medicalTaskId: 'TSK-MED-002',
    medicalStatus: 'completed',
    medicalAssignedTo: 'usr-med-001',
    rigId: 'AD-201',
  },
  {
    id: 'ONB-007',
    name: 'Hamid Al-Balushi',
    company: 'Oman Oil Services',
    role: 'Floorhand',
    nationality: 'Omani',
    passportNumber: 'OM3344556',
    emergencyContact: 'Aisha Al-Balushi',
    emergencyPhone: '+968-9900-1122',
    arrivalDate: '2026-03-01',
    status: 'tasks_created',
    trainingTaskId: 'TSK-ONB-007',
    trainingStatus: 'in_progress',
    trainingAssignedTo: 'usr-hse-001',
    medicalTaskId: 'TSK-MED-007',
    medicalStatus: 'pending',
    medicalAssignedTo: 'usr-med-001',
    rigId: 'AD-201',
  },
  {
    id: 'ONB-008',
    name: 'Vasile Ionescu',
    company: 'Petrom Services',
    role: 'Mud Engineer',
    nationality: 'Romanian',
    passportNumber: 'RO8899001',
    emergencyContact: 'Elena Ionescu',
    emergencyPhone: '+40-723-889-900',
    arrivalDate: '2026-03-02',
    status: 'ready_for_checkin',
    trainingTaskId: 'TSK-ONB-008',
    trainingStatus: 'completed',
    trainingAssignedTo: 'usr-hse-001',
    medicalTaskId: 'TSK-MED-008',
    medicalStatus: 'completed',
    medicalAssignedTo: 'usr-med-001',
    rigId: 'AD-201',
  },
  {
    id: 'ONB-009',
    name: 'Kwame Asante',
    company: 'Tullow Oil Services',
    role: 'Drilling Supervisor',
    nationality: 'Ghanaian',
    passportNumber: 'GH1234890',
    emergencyContact: 'Abena Asante',
    emergencyPhone: '+233-24-123-4567',
    arrivalDate: '2026-03-03',
    status: 'info_submitted',
    trainingTaskId: null,
    trainingStatus: 'not_created',
    trainingAssignedTo: null,
    medicalTaskId: null,
    medicalStatus: 'not_created',
    medicalAssignedTo: null,
    rigId: 'AD-201',
  },
  {
    id: 'ONB-010',
    name: 'Marco Ricci',
    company: 'Saipem',
    role: 'Crane Operator',
    nationality: 'Italian',
    passportNumber: 'IT7788990',
    emergencyContact: 'Giulia Ricci',
    emergencyPhone: '+39-338-778-9900',
    arrivalDate: '2026-03-04',
    status: 'pending_info',
    trainingTaskId: null,
    trainingStatus: 'not_created',
    trainingAssignedTo: null,
    medicalTaskId: null,
    medicalStatus: 'not_created',
    medicalAssignedTo: null,
    rigId: 'AD-201',
  },
];
