// ============================================================
// PERSONNEL / POB (Personnel on Board) DUMMY DATA
// Oil & Gas Operations Management Platform — ADI
// ============================================================

export type PersonnelType =
  | 'adi_employee'
  | 'contractor'
  | 'vendor_service'
  | 'operator_rep'
  | 'government_inspector';

export type PersonnelStatus =
  | 'onboard'
  | 'on_leave'
  | 'mobilising'
  | 'demobilising'
  | 'standby_base';

export type BloodGroup = 'A+' | 'A-' | 'B+' | 'B-' | 'O+' | 'O-' | 'AB+' | 'AB-';

export interface MedicalInfo {
  bloodGroup: BloodGroup;
  medicalCertExpiry: string;
  h2sMedicalClearance: boolean;
  specialRequirements?: string;
}

export interface Certification {
  name: string;
  issuedBy: string;
  issuedDate: string;
  expiryDate: string;
  certNumber: string;
  status: 'valid' | 'expiring_soon' | 'expired';
}

export interface PersonnelRecord {
  id: string;
  name: string;
  initials: string;
  nationality: string;
  passportNumber: string;
  passportExpiry: string;
  iqamaNumber?: string;
  iqamaExpiry?: string;
  employeeId?: string;
  vendorId?: string;
  company: string;
  type: PersonnelType;
  jobTitle: string;
  department: string;
  rigId: string | null;
  rigName: string | null;
  status: PersonnelStatus;
  mobDate?: string;
  demobDate?: string;
  rotationCycle: string;
  currentRotationEnd?: string;
  emergencyContactName: string;
  emergencyContactPhone: string;
  emergencyContactRelation: string;
  medical: MedicalInfo;
  certifications: Certification[];
  avatarColor: string;
  phone?: string;
  email?: string;
}

export const PERSONNEL: PersonnelRecord[] = [
  // ── RIG ALPHA (AD-201) ─────────────────────────────────────────────
  {
    id: 'PER-001',
    name: 'Omar Hassan',
    initials: 'OH',
    nationality: 'Saudi Arabian',
    passportNumber: 'SA-8812340',
    passportExpiry: '2028-05-15',
    iqamaNumber: 'IQ-1012345678',
    iqamaExpiry: '2026-09-30',
    employeeId: 'ADI-EMP-0045',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Rig Manager',
    department: 'Rig Operations',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    status: 'onboard',
    mobDate: '2025-09-14',
    rotationCycle: '28 days on / 28 days off',
    currentRotationEnd: '2026-03-14',
    emergencyContactName: 'Layla Hassan',
    emergencyContactPhone: '+966-50-987-0001',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'O+',
      medicalCertExpiry: '2026-09-14',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'IWCF Supervisor Level 4',
        issuedBy: 'IWCF',
        issuedDate: '2023-06-10',
        expiryDate: '2025-06-10',
        certNumber: 'IWCF-SUP-2023-44821',
        status: 'expired',
      },
      {
        name: 'BOSIET (Offshore Safety)',
        issuedBy: 'OPITO',
        issuedDate: '2024-01-15',
        expiryDate: '2028-01-15',
        certNumber: 'OPITO-BST-2024-7821',
        status: 'valid',
      },
    ],
    avatarColor: '#00897B',
    phone: '+966-50-123-4505',
    email: 'o.hassan@adi-drilling.com',
  },
  {
    id: 'PER-002',
    name: 'Mohammed Al-Dosari',
    initials: 'MD',
    nationality: 'Saudi Arabian',
    passportNumber: 'SA-9923450',
    passportExpiry: '2027-11-20',
    iqamaNumber: 'IQ-1023456789',
    iqamaExpiry: '2026-11-30',
    employeeId: 'ADI-EMP-0062',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Well Control Specialist / Senior Driller',
    department: 'Drilling Engineering',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    status: 'onboard',
    mobDate: '2025-09-14',
    rotationCycle: '28 days on / 28 days off',
    currentRotationEnd: '2026-03-14',
    emergencyContactName: 'Hessa Al-Dosari',
    emergencyContactPhone: '+966-50-987-0002',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'A+',
      medicalCertExpiry: '2026-06-30',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'IWCF Supervisor Level 4',
        issuedBy: 'IWCF',
        issuedDate: '2024-04-15',
        expiryDate: '2026-04-15',
        certNumber: 'IWCF-SUP-2024-51234',
        status: 'valid',
      },
      {
        name: 'H2S Awareness (TBOSIET)',
        issuedBy: 'OPITO',
        issuedDate: '2023-08-01',
        expiryDate: '2027-08-01',
        certNumber: 'OPITO-H2S-2023-9901',
        status: 'valid',
      },
    ],
    avatarColor: '#BF360C',
    phone: '+966-50-123-4518',
    email: 'm.aldosari@adi-drilling.com',
  },
  {
    id: 'PER-003',
    name: 'Khalid Mahmoud',
    initials: 'KM',
    nationality: 'Egyptian',
    passportNumber: 'EG-A1234567',
    passportExpiry: '2026-08-10',
    iqamaNumber: 'IQ-2012345670',
    iqamaExpiry: '2026-08-31',
    employeeId: 'ADI-EMP-0028',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Maintenance Manager',
    department: 'Maintenance',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    status: 'onboard',
    mobDate: '2025-09-14',
    rotationCycle: '28 days on / 28 days off',
    currentRotationEnd: '2026-03-14',
    emergencyContactName: 'Nour Mahmoud',
    emergencyContactPhone: '+20-10-9870-002',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'B+',
      medicalCertExpiry: '2026-10-01',
      h2sMedicalClearance: true,
      specialRequirements: 'Carries prescribed blood pressure medication.',
    },
    certifications: [
      {
        name: 'IWCF Well Control (Driller Level)',
        issuedBy: 'IWCF',
        issuedDate: '2023-11-05',
        expiryDate: '2025-11-05',
        certNumber: 'IWCF-DRL-2023-38844',
        status: 'expired',
      },
    ],
    avatarColor: '#0277BD',
    phone: '+966-50-123-4508',
    email: 'k.mahmoud@adi-drilling.com',
  },
  {
    id: 'PER-004',
    name: 'Ali Hassan',
    initials: 'AH',
    nationality: 'Pakistani',
    passportNumber: 'PK-CP1234567',
    passportExpiry: '2027-03-25',
    iqamaNumber: 'IQ-2034567890',
    iqamaExpiry: '2027-03-31',
    employeeId: 'ADI-EMP-0071',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'HSE Officer',
    department: 'HSE',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    status: 'onboard',
    mobDate: '2025-09-14',
    rotationCycle: '28 days on / 28 days off',
    currentRotationEnd: '2026-03-14',
    emergencyContactName: 'Fatima Hassan',
    emergencyContactPhone: '+92-300-9870003',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'O+',
      medicalCertExpiry: '2026-12-01',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'NEBOSH IGC',
        issuedBy: 'NEBOSH',
        issuedDate: '2022-06-20',
        expiryDate: '2027-06-20',
        certNumber: 'NEBOSH-IGC-2022-78901',
        status: 'valid',
      },
      {
        name: 'OPITO H2S Awareness',
        issuedBy: 'OPITO',
        issuedDate: '2024-02-10',
        expiryDate: '2028-02-10',
        certNumber: 'OPITO-H2S-2024-11122',
        status: 'valid',
      },
    ],
    avatarColor: '#2E7D32',
    phone: '+966-50-123-4509',
    email: 'a.hassan@adi-drilling.com',
  },
  {
    id: 'PER-005',
    name: 'Emma Richards',
    initials: 'ER',
    nationality: 'British',
    passportNumber: 'GB-123456789',
    passportExpiry: '2028-07-14',
    iqamaNumber: 'IQ-2045678901',
    iqamaExpiry: '2027-01-31',
    employeeId: 'ADI-EMP-0053',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Quality Engineer',
    department: 'Quality',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    status: 'onboard',
    mobDate: '2026-01-15',
    rotationCycle: '14 days on / 14 days off',
    currentRotationEnd: '2026-03-01',
    emergencyContactName: 'David Richards',
    emergencyContactPhone: '+44-790-987-0004',
    emergencyContactRelation: 'Father',
    medical: {
      bloodGroup: 'A-',
      medicalCertExpiry: '2026-07-01',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'ISO 9001:2015 Lead Auditor',
        issuedBy: 'CQI-IRCA',
        issuedDate: '2022-03-15',
        expiryDate: '2027-03-15',
        certNumber: 'IRCA-LA-2022-44521',
        status: 'valid',
      },
    ],
    avatarColor: '#E91E63',
    phone: '+966-50-123-4502',
    email: 'e.richards@adi-drilling.com',
  },
  {
    id: 'PER-006',
    name: 'Jack Anderson',
    initials: 'JA',
    nationality: 'American',
    passportNumber: 'US-456789123',
    passportExpiry: '2027-09-30',
    iqamaNumber: 'IQ-2056789012',
    iqamaExpiry: '2026-10-31',
    vendorId: 'BH-VENDOR-4521',
    company: 'Halliburton Drilling & Evaluation',
    type: 'vendor_service',
    jobTitle: 'Mud Logging Unit Supervisor',
    department: 'Mud Logging',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    status: 'onboard',
    mobDate: '2026-01-01',
    rotationCycle: '28 days on / 28 days off',
    currentRotationEnd: '2026-03-01',
    emergencyContactName: 'Carol Anderson',
    emergencyContactPhone: '+1-713-987-0005',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'B-',
      medicalCertExpiry: '2026-11-01',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'IWCF Driller Level',
        issuedBy: 'IWCF',
        issuedDate: '2024-03-01',
        expiryDate: '2026-03-01',
        certNumber: 'IWCF-DRL-2024-55128',
        status: 'expiring_soon',
      },
    ],
    avatarColor: '#546E7A',
    phone: '+966-50-555-1001',
    email: 'j.anderson@halliburton.com',
  },
  {
    id: 'PER-007',
    name: 'Tariq Al-Shammari',
    initials: 'TS',
    nationality: 'Saudi Arabian',
    passportNumber: 'SA-7734521',
    passportExpiry: '2028-01-10',
    iqamaNumber: 'IQ-1034567890',
    iqamaExpiry: '2027-01-10',
    vendorId: 'SA-ARAMCO-REP-0021',
    company: 'Saudi Aramco (Operator Representative)',
    type: 'operator_rep',
    jobTitle: 'Aramco Company Man (Senior Drilling Engineer)',
    department: 'Drilling Engineering',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    status: 'onboard',
    mobDate: '2025-10-01',
    rotationCycle: '14 days on / 14 days off',
    currentRotationEnd: '2026-03-08',
    emergencyContactName: 'Maha Al-Shammari',
    emergencyContactPhone: '+966-50-987-0006',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'O-',
      medicalCertExpiry: '2027-01-10',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'IADC WellSharp Supervisor',
        issuedBy: 'IADC',
        issuedDate: '2024-08-20',
        expiryDate: '2026-08-20',
        certNumber: 'IADC-WS-SUP-2024-10044',
        status: 'valid',
      },
    ],
    avatarColor: '#FF8F00',
    phone: '+966-50-555-2001',
    email: 't.alshammari@aramco.com',
  },
  {
    id: 'PER-008',
    name: 'Ricardo Santos',
    initials: 'RS',
    nationality: 'Brazilian',
    passportNumber: 'BR-AA1234567',
    passportExpiry: '2026-04-15',
    iqamaNumber: 'IQ-2067890123',
    iqamaExpiry: '2026-04-30',
    vendorId: 'NOV-VENDOR-0891',
    company: 'NOV Rig Services',
    type: 'vendor_service',
    jobTitle: 'Top Drive Field Service Engineer',
    department: 'Maintenance',
    rigId: 'AD-201',
    rigName: 'Rig Alpha',
    status: 'onboard',
    mobDate: '2026-02-24',
    demobDate: '2026-03-10',
    rotationCycle: 'Project-based',
    currentRotationEnd: '2026-03-10',
    emergencyContactName: 'Ana Santos',
    emergencyContactPhone: '+55-21-9870-0007',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'A+',
      medicalCertExpiry: '2027-04-15',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'NOV TDS-11SA Service Certification',
        issuedBy: 'National Oilwell Varco',
        issuedDate: '2023-05-10',
        expiryDate: '2028-05-10',
        certNumber: 'NOV-TDS11SA-SVC-2023-4421',
        status: 'valid',
      },
    ],
    avatarColor: '#00838F',
    phone: '+966-50-555-3001',
    email: 'r.santos@nov.com',
  },

  // ── RIG BRAVO (AD-202) ─────────────────────────────────────────────
  {
    id: 'PER-009',
    name: 'Carlos Mendez',
    initials: 'CM',
    nationality: 'Mexican',
    passportNumber: 'MX-G98765432',
    passportExpiry: '2027-06-25',
    iqamaNumber: 'IQ-2078901234',
    iqamaExpiry: '2026-07-31',
    employeeId: 'ADI-EMP-0039',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Rig Manager',
    department: 'Rig Operations',
    rigId: 'AD-202',
    rigName: 'Rig Bravo',
    status: 'onboard',
    mobDate: '2025-10-02',
    rotationCycle: '28 days on / 28 days off',
    currentRotationEnd: '2026-03-30',
    emergencyContactName: 'Maria Mendez',
    emergencyContactPhone: '+52-55-9870-0008',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'AB+',
      medicalCertExpiry: '2026-10-02',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'IADC WellSharp Supervisor',
        issuedBy: 'IADC',
        issuedDate: '2024-09-01',
        expiryDate: '2026-09-01',
        certNumber: 'IADC-WS-SUP-2024-10088',
        status: 'valid',
      },
    ],
    avatarColor: '#E65100',
    phone: '+966-50-123-4515',
    email: 'c.mendez@adi-drilling.com',
  },
  {
    id: 'PER-010',
    name: 'Nadia Petrova',
    initials: 'NP',
    nationality: 'Russian',
    passportNumber: 'RU-700123456',
    passportExpiry: '2028-03-14',
    iqamaNumber: 'IQ-2089012345',
    iqamaExpiry: '2027-03-31',
    employeeId: 'ADI-EMP-0058',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Drilling Engineer',
    department: 'Drilling Engineering',
    rigId: 'AD-202',
    rigName: 'Rig Bravo',
    status: 'onboard',
    mobDate: '2026-01-10',
    rotationCycle: '14 days on / 14 days off',
    currentRotationEnd: '2026-03-10',
    emergencyContactName: 'Alexei Petrov',
    emergencyContactPhone: '+7-495-987-0009',
    emergencyContactRelation: 'Father',
    medical: {
      bloodGroup: 'B+',
      medicalCertExpiry: '2027-01-10',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'IWCF Supervisor Level 4',
        issuedBy: 'IWCF',
        issuedDate: '2024-01-20',
        expiryDate: '2026-01-20',
        certNumber: 'IWCF-SUP-2024-50012',
        status: 'expiring_soon',
      },
      {
        name: 'SPE Member — Drilling Engineering',
        issuedBy: 'Society of Petroleum Engineers',
        issuedDate: '2019-06-01',
        expiryDate: '2099-01-01',
        certNumber: 'SPE-4521098',
        status: 'valid',
      },
    ],
    avatarColor: '#AD1457',
    phone: '+966-50-123-4514',
    email: 'n.petrova@adi-drilling.com',
  },
  {
    id: 'PER-011',
    name: 'David Chen',
    initials: 'DC',
    nationality: 'Canadian',
    passportNumber: 'CA-AB123456',
    passportExpiry: '2029-02-20',
    iqamaNumber: 'IQ-2090123456',
    iqamaExpiry: '2027-02-28',
    employeeId: 'ADI-EMP-0065',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Quality Engineer',
    department: 'Quality',
    rigId: 'AD-202',
    rigName: 'Rig Bravo',
    status: 'onboard',
    mobDate: '2026-02-01',
    rotationCycle: '14 days on / 14 days off',
    currentRotationEnd: '2026-03-01',
    emergencyContactName: 'Lisa Chen',
    emergencyContactPhone: '+1-604-987-0010',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'O+',
      medicalCertExpiry: '2026-10-01',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'ISO 9001:2015 Internal Auditor',
        issuedBy: 'BSI',
        issuedDate: '2023-09-10',
        expiryDate: '2028-09-10',
        certNumber: 'BSI-IA-2023-91022',
        status: 'valid',
      },
    ],
    avatarColor: '#C62828',
    phone: '+966-50-123-4510',
    email: 'd.chen@adi-drilling.com',
  },
  {
    id: 'PER-012',
    name: 'Ahmed Al-Rashid',
    initials: 'AR',
    nationality: 'Jordanian',
    passportNumber: 'JO-K1234567',
    passportExpiry: '2027-07-01',
    iqamaNumber: 'IQ-2101234567',
    iqamaExpiry: '2026-07-31',
    employeeId: 'ADI-EMP-0041',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Quality Manager',
    department: 'Quality',
    rigId: 'AD-202',
    rigName: 'Rig Bravo',
    status: 'onboard',
    mobDate: '2025-10-02',
    rotationCycle: '28 days on / 28 days off',
    currentRotationEnd: '2026-03-30',
    emergencyContactName: 'Hana Al-Rashid',
    emergencyContactPhone: '+962-79-987-0011',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'A+',
      medicalCertExpiry: '2027-07-01',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'ISO 9001:2015 Lead Auditor',
        issuedBy: 'CQI-IRCA',
        issuedDate: '2020-05-15',
        expiryDate: '2025-05-15',
        certNumber: 'IRCA-LA-2020-31244',
        status: 'expired',
      },
    ],
    avatarColor: '#F4511E',
    phone: '+966-50-123-4506',
    email: 'a.alrashid@adi-drilling.com',
  },
  {
    id: 'PER-013',
    name: 'Bjorn Andersen',
    initials: 'BA',
    nationality: 'Norwegian',
    passportNumber: 'NO-12345678',
    passportExpiry: '2028-08-30',
    iqamaNumber: 'IQ-2112345678',
    iqamaExpiry: '2026-09-30',
    vendorId: 'SLB-VENDOR-1122',
    company: 'Schlumberger Drilling Services',
    type: 'vendor_service',
    jobTitle: 'MWD/LWD Field Engineer',
    department: 'Directional Drilling',
    rigId: 'AD-202',
    rigName: 'Rig Bravo',
    status: 'onboard',
    mobDate: '2025-11-01',
    rotationCycle: '28 days on / 28 days off',
    currentRotationEnd: '2026-03-01',
    emergencyContactName: 'Ingrid Andersen',
    emergencyContactPhone: '+47-400-98700',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'A+',
      medicalCertExpiry: '2027-08-30',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'IWCF Well Control (Driller Level)',
        issuedBy: 'IWCF',
        issuedDate: '2023-10-05',
        expiryDate: '2025-10-05',
        certNumber: 'IWCF-DRL-2023-41007',
        status: 'expired',
      },
    ],
    avatarColor: '#37474F',
    phone: '+966-50-555-4001',
    email: 'b.andersen@slb.com',
  },
  {
    id: 'PER-014',
    name: 'Peter Okafor',
    initials: 'PO',
    nationality: 'Nigerian',
    passportNumber: 'NG-A12345678',
    passportExpiry: '2026-12-10',
    iqamaNumber: 'IQ-2123456789',
    iqamaExpiry: '2026-12-31',
    employeeId: 'ADI-EMP-0077',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'HSE Coordinator',
    department: 'HSE',
    rigId: 'AD-203',
    rigName: 'Rig Charlie',
    status: 'onboard',
    mobDate: '2025-11-18',
    rotationCycle: '28 days on / 28 days off',
    currentRotationEnd: '2026-03-18',
    emergencyContactName: 'Grace Okafor',
    emergencyContactPhone: '+234-802-987-0012',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'O+',
      medicalCertExpiry: '2026-08-10',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'NEBOSH IGC',
        issuedBy: 'NEBOSH',
        issuedDate: '2021-10-15',
        expiryDate: '2026-10-15',
        certNumber: 'NEBOSH-IGC-2021-61098',
        status: 'valid',
      },
      {
        name: 'OPITO BOSIET',
        issuedBy: 'OPITO',
        issuedDate: '2023-06-01',
        expiryDate: '2027-06-01',
        certNumber: 'OPITO-BST-2023-5521',
        status: 'valid',
      },
    ],
    avatarColor: '#00695C',
    phone: '+966-50-123-4516',
    email: 'p.okafor@adi-drilling.com',
  },
  {
    id: 'PER-015',
    name: 'Tom Bradshaw',
    initials: 'TB',
    nationality: 'Australian',
    passportNumber: 'AU-N9876543',
    passportExpiry: '2027-04-25',
    iqamaNumber: 'IQ-2134567890',
    iqamaExpiry: '2026-05-31',
    employeeId: 'ADI-EMP-0032',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Rig Manager',
    department: 'Rig Operations',
    rigId: 'AD-203',
    rigName: 'Rig Charlie',
    status: 'onboard',
    mobDate: '2025-11-18',
    rotationCycle: '28 days on / 28 days off',
    currentRotationEnd: '2026-03-18',
    emergencyContactName: 'Sarah Bradshaw',
    emergencyContactPhone: '+61-400-987-0013',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'B+',
      medicalCertExpiry: '2027-04-25',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'IADC WellSharp Supervisor',
        issuedBy: 'IADC',
        issuedDate: '2025-01-10',
        expiryDate: '2027-01-10',
        certNumber: 'IADC-WS-SUP-2025-12001',
        status: 'valid',
      },
    ],
    avatarColor: '#006064',
    phone: '+966-50-123-4522',
    email: 't.bradshaw@adi-drilling.com',
  },
  {
    id: 'PER-016',
    name: 'Sami Al-Otaibi',
    initials: 'SO',
    nationality: 'Saudi Arabian',
    passportNumber: 'SA-6643210',
    passportExpiry: '2029-02-08',
    iqamaNumber: 'IQ-1045678901',
    iqamaExpiry: '2027-02-28',
    employeeId: 'ADI-EMP-0083',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Mechanical Supervisor',
    department: 'Maintenance',
    rigId: 'AD-203',
    rigName: 'Rig Charlie',
    status: 'onboard',
    mobDate: '2025-11-18',
    rotationCycle: '28 days on / 28 days off',
    currentRotationEnd: '2026-03-18',
    emergencyContactName: 'Wafa Al-Otaibi',
    emergencyContactPhone: '+966-50-987-0014',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'O+',
      medicalCertExpiry: '2026-09-08',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'IWCF Well Control (Driller Level)',
        issuedBy: 'IWCF',
        issuedDate: '2024-07-15',
        expiryDate: '2026-07-15',
        certNumber: 'IWCF-DRL-2024-58821',
        status: 'valid',
      },
    ],
    avatarColor: '#33691E',
    phone: '+966-50-123-4519',
    email: 's.alotaibi@adi-drilling.com',
  },
  {
    id: 'PER-017',
    name: 'Sarah Mitchell',
    initials: 'SM',
    nationality: 'Irish',
    passportNumber: 'IE-P1234567',
    passportExpiry: '2028-10-12',
    iqamaNumber: 'IQ-2145678902',
    iqamaExpiry: '2027-10-31',
    employeeId: 'ADI-EMP-0059',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Quality Manager',
    department: 'Quality',
    rigId: 'AD-203',
    rigName: 'Rig Charlie',
    status: 'onboard',
    mobDate: '2025-11-18',
    rotationCycle: '28 days on / 28 days off',
    currentRotationEnd: '2026-03-18',
    emergencyContactName: 'Michael Mitchell',
    emergencyContactPhone: '+353-86-987-0015',
    emergencyContactRelation: 'Father',
    medical: {
      bloodGroup: 'A+',
      medicalCertExpiry: '2026-10-12',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'ISO 9001:2015 Lead Auditor',
        issuedBy: 'CQI-IRCA',
        issuedDate: '2021-11-20',
        expiryDate: '2026-11-20',
        certNumber: 'IRCA-LA-2021-36678',
        status: 'valid',
      },
    ],
    avatarColor: '#7B1FA2',
    phone: '+966-50-123-4507',
    email: 's.mitchell@adi-drilling.com',
  },

  // ── HQ / BASE (not onboard rig) ────────────────────────────────────
  {
    id: 'PER-018',
    name: 'Hassan Al-Qahtani',
    initials: 'HQ',
    nationality: 'Saudi Arabian',
    passportNumber: 'SA-5534120',
    passportExpiry: '2028-01-20',
    iqamaNumber: 'IQ-1056789012',
    iqamaExpiry: '2028-01-31',
    employeeId: 'ADI-EMP-0001',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Quality Manager (Corporate)',
    department: 'Quality',
    rigId: null,
    rigName: null,
    status: 'standby_base',
    rotationCycle: 'Office-based (Dammam HQ)',
    emergencyContactName: 'Lina Al-Qahtani',
    emergencyContactPhone: '+966-50-987-0016',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'AB+',
      medicalCertExpiry: '2027-01-20',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'ISO 9001:2015 Lead Auditor',
        issuedBy: 'CQI-IRCA',
        issuedDate: '2019-04-10',
        expiryDate: '2024-04-10',
        certNumber: 'IRCA-LA-2019-22114',
        status: 'expired',
      },
    ],
    avatarColor: '#1A73E8',
    phone: '+966-50-123-4501',
    email: 'h.alqahtani@adi-drilling.com',
  },
  {
    id: 'PER-019',
    name: 'James Cooper',
    initials: 'JC',
    nationality: 'British',
    passportNumber: 'GB-987654321',
    passportExpiry: '2027-11-05',
    iqamaNumber: 'IQ-2156789013',
    iqamaExpiry: '2026-11-30',
    employeeId: 'ADI-EMP-0015',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Rig Superintendent',
    department: 'Rig Operations',
    rigId: null,
    rigName: null,
    status: 'standby_base',
    rotationCycle: 'Office-based (Dammam HQ) / Rig visit as required',
    emergencyContactName: 'Patricia Cooper',
    emergencyContactPhone: '+44-770-987-0017',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'O+',
      medicalCertExpiry: '2026-11-05',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'IADC WellSharp Supervisor',
        issuedBy: 'IADC',
        issuedDate: '2024-10-01',
        expiryDate: '2026-10-01',
        certNumber: 'IADC-WS-SUP-2024-10999',
        status: 'valid',
      },
    ],
    avatarColor: '#1565C0',
    phone: '+966-50-123-4513',
    email: 'j.cooper@adi-drilling.com',
  },
  {
    id: 'PER-020',
    name: 'Abdullah Qasim',
    initials: 'AQ',
    nationality: 'Pakistani',
    passportNumber: 'PK-BB9876543',
    passportExpiry: '2027-08-15',
    iqamaNumber: 'IQ-2167890124',
    iqamaExpiry: '2026-08-31',
    employeeId: 'ADI-EMP-0022',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Asset Manager',
    department: 'Asset Management',
    rigId: null,
    rigName: null,
    status: 'standby_base',
    rotationCycle: 'Office-based (Dammam HQ)',
    emergencyContactName: 'Ayesha Qasim',
    emergencyContactPhone: '+92-311-987-0018',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'B+',
      medicalCertExpiry: '2026-08-15',
      h2sMedicalClearance: true,
    },
    certifications: [],
    avatarColor: '#1A237E',
    phone: '+966-50-123-4520',
    email: 'a.qasim@adi-drilling.com',
  },
  {
    id: 'PER-021',
    name: 'Khalid Al-Harbi',
    initials: 'KH',
    nationality: 'Saudi Arabian',
    passportNumber: 'SA-4423100',
    passportExpiry: '2026-06-30',
    iqamaNumber: 'IQ-1067890125',
    iqamaExpiry: '2026-06-30',
    employeeId: 'ADI-EMP-0033',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Supply Chain Manager',
    department: 'Supply Chain',
    rigId: null,
    rigName: null,
    status: 'standby_base',
    rotationCycle: 'Office-based (Dammam HQ)',
    emergencyContactName: 'Noura Al-Harbi',
    emergencyContactPhone: '+966-50-987-0019',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'A+',
      medicalCertExpiry: '2026-06-30',
      h2sMedicalClearance: false,
    },
    certifications: [],
    avatarColor: '#6A1B9A',
    phone: '+966-50-123-4512',
    email: 'k.alharbi@adi-drilling.com',
  },
  {
    id: 'PER-022',
    name: 'Yusuf Ibrahim',
    initials: 'YI',
    nationality: 'Bangladeshi',
    passportNumber: 'BD-AA1234567',
    passportExpiry: '2027-12-01',
    iqamaNumber: 'IQ-2178901235',
    iqamaExpiry: '2026-12-31',
    employeeId: 'ADI-EMP-0091',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Warehouse Supervisor',
    department: 'Warehouse',
    rigId: null,
    rigName: null,
    status: 'standby_base',
    rotationCycle: 'Base-based (Dammam Base)',
    emergencyContactName: 'Rahela Ibrahim',
    emergencyContactPhone: '+880-171-987-0020',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'O-',
      medicalCertExpiry: '2026-12-01',
      h2sMedicalClearance: false,
    },
    certifications: [],
    avatarColor: '#558B2F',
    phone: '+966-50-123-4511',
    email: 'y.ibrahim@adi-drilling.com',
  },
  {
    id: 'PER-023',
    name: 'Andrew Campbell',
    initials: 'AC',
    nationality: 'Scottish',
    passportNumber: 'GB-123789456',
    passportExpiry: '2027-05-10',
    iqamaNumber: 'IQ-2189012346',
    iqamaExpiry: '2026-06-30',
    employeeId: 'ADI-EMP-0047',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Lead Auditor / QMS Specialist',
    department: 'Quality',
    rigId: null,
    rigName: null,
    status: 'standby_base',
    rotationCycle: 'Office-based / Rig audits as required',
    emergencyContactName: 'Fiona Campbell',
    emergencyContactPhone: '+44-741-987-0021',
    emergencyContactRelation: 'Spouse',
    medical: {
      bloodGroup: 'A-',
      medicalCertExpiry: '2026-05-10',
      h2sMedicalClearance: true,
    },
    certifications: [
      {
        name: 'ISO 9001:2015 Lead Auditor (IRCA)',
        issuedBy: 'CQI-IRCA',
        issuedDate: '2018-09-01',
        expiryDate: '2023-09-01',
        certNumber: 'IRCA-LA-2018-15342',
        status: 'expired',
      },
      {
        name: 'IADC RigPass Auditor',
        issuedBy: 'IADC',
        issuedDate: '2022-04-15',
        expiryDate: '2027-04-15',
        certNumber: 'IADC-RPA-2022-7732',
        status: 'valid',
      },
    ],
    avatarColor: '#FF6D00',
    phone: '+966-50-123-4503',
    email: 'a.campbell@adi-drilling.com',
  },
  {
    id: 'PER-024',
    name: 'Fatima Al-Subaie',
    initials: 'FS',
    nationality: 'Saudi Arabian',
    passportNumber: 'SA-3312405',
    passportExpiry: '2027-09-15',
    iqamaNumber: 'IQ-1078901236',
    iqamaExpiry: '2027-09-30',
    employeeId: 'ADI-EMP-0095',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Document Controller',
    department: 'Quality',
    rigId: null,
    rigName: null,
    status: 'standby_base',
    rotationCycle: 'Office-based (Dammam HQ)',
    emergencyContactName: 'Ali Al-Subaie',
    emergencyContactPhone: '+966-50-987-0022',
    emergencyContactRelation: 'Father',
    medical: {
      bloodGroup: 'AB-',
      medicalCertExpiry: '2027-09-15',
      h2sMedicalClearance: false,
    },
    certifications: [],
    avatarColor: '#9C27B0',
    phone: '+966-50-123-4504',
    email: 'f.alsubaie@adi-drilling.com',
  },
  {
    id: 'PER-025',
    name: 'Tariq Nasser',
    initials: 'TN',
    nationality: 'Saudi Arabian',
    passportNumber: 'SA-2201344',
    passportExpiry: '2028-11-22',
    iqamaNumber: 'IQ-1089012347',
    iqamaExpiry: '2027-11-30',
    employeeId: 'ADI-EMP-0098',
    company: 'ADI Drilling LLC',
    type: 'adi_employee',
    jobTitle: 'Warehouse Clerk',
    department: 'Warehouse',
    rigId: null,
    rigName: null,
    status: 'standby_base',
    rotationCycle: 'Base-based (Dammam Base)',
    emergencyContactName: 'Hassan Nasser',
    emergencyContactPhone: '+966-50-987-0023',
    emergencyContactRelation: 'Father',
    medical: {
      bloodGroup: 'O+',
      medicalCertExpiry: '2027-11-22',
      h2sMedicalClearance: false,
    },
    certifications: [],
    avatarColor: '#4527A0',
    phone: '+966-50-123-4517',
    email: 't.nasser@adi-drilling.com',
  },
];

// POB summary by rig
export const POB_SUMMARY = {
  'AD-201': {
    rigName: 'Rig Alpha',
    onboard: PERSONNEL.filter((p) => p.rigId === 'AD-201' && p.status === 'onboard').length,
    maxPOB: 80,
  },
  'AD-202': {
    rigName: 'Rig Bravo',
    onboard: PERSONNEL.filter((p) => p.rigId === 'AD-202' && p.status === 'onboard').length,
    maxPOB: 80,
  },
  'AD-203': {
    rigName: 'Rig Charlie',
    onboard: PERSONNEL.filter((p) => p.rigId === 'AD-203' && p.status === 'onboard').length,
    maxPOB: 80,
  },
};

export const getPersonnelById = (id: string): PersonnelRecord | undefined =>
  PERSONNEL.find((p) => p.id === id);

export const getPersonnelByRig = (rigId: string): PersonnelRecord[] =>
  PERSONNEL.filter((p) => p.rigId === rigId);

export const getExpiringCertifications = (withinDays = 90): { person: PersonnelRecord; cert: Certification }[] => {
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() + withinDays);
  const results: { person: PersonnelRecord; cert: Certification }[] = [];
  PERSONNEL.forEach((p) => {
    p.certifications.forEach((cert) => {
      const expiry = new Date(cert.expiryDate);
      if (expiry <= cutoff && cert.status !== 'expired') {
        results.push({ person: p, cert });
      }
    });
  });
  return results;
};
