// ============================================================
// WAREHOUSE / INVENTORY DUMMY DATA
// Oil & Gas Operations Management Platform — ADI
// ============================================================

export type ItemCategory =
  | 'ppe'
  | 'spares_mechanical'
  | 'spares_electrical'
  | 'spares_well_control'
  | 'capital_goods'
  | 'tools_hand'
  | 'tools_power'
  | 'drill_string'
  | 'mud_chemicals'
  | 'cement_chemicals'
  | 'consumables'
  | 'safety_equipment'
  | 'tubular_goods';

export type StockStatus =
  | 'in_stock'
  | 'low_stock'
  | 'out_of_stock'
  | 'on_order'
  | 'quarantine'
  | 'reserved';

export type UnitOfMeasure =
  | 'each'
  | 'set'
  | 'kg'
  | 'litre'
  | 'metre'
  | 'box'
  | 'pallet'
  | 'drum'
  | 'spool'
  | 'pair'
  | 'bag'
  | 'joint'
  | 'ft';

export interface InventoryItem {
  id: string;
  partNumber: string;
  oemPartNumber?: string;
  description: string;
  category: ItemCategory;
  manufacturer: string;
  unit: UnitOfMeasure;
  currentStock: number;
  minStockLevel: number;
  maxStockLevel: number;
  reorderPoint: number;
  reorderQty: number;
  status: StockStatus;
  location: string;
  binLocation: string;
  unitCostSAR: number;
  totalValueSAR: number;
  lastReceivedDate: string;
  lastIssuedDate?: string;
  lastIssuedTo?: string;
  supplierName: string;
  supplierPartNumber?: string;
  leadTimeDays: number;
  expiryDate?: string;
  isCriticalSpare: boolean;
  applicableRigs: string[];
  tags: string[];
  notes?: string;
}

export const INVENTORY_ITEMS: InventoryItem[] = [
  // ── PPE ─────────────────────────────────────────────────────────────
  {
    id: 'WH-PPE-001',
    partNumber: 'ADI-PPE-HELM-001',
    oemPartNumber: 'MSA-V-GARD-WHITE',
    description: 'Safety Helmet — MSA V-Gard, White (Supervisors)',
    category: 'ppe',
    manufacturer: 'MSA Safety',
    unit: 'each',
    currentStock: 85,
    minStockLevel: 40,
    maxStockLevel: 200,
    reorderPoint: 50,
    reorderQty: 100,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'A-01-01',
    unitCostSAR: 65,
    totalValueSAR: 5525,
    lastReceivedDate: '2025-12-15',
    lastIssuedDate: '2026-02-10',
    lastIssuedTo: 'Rig Alpha — Crew Rotation',
    supplierName: 'MSA Safety Arabia',
    supplierPartNumber: 'MSA-10034018',
    leadTimeDays: 7,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['PPE', 'Helmet', 'Supervisor', 'Head Protection'],
  },
  {
    id: 'WH-PPE-002',
    partNumber: 'ADI-PPE-HELM-002',
    oemPartNumber: 'MSA-V-GARD-YELLOW',
    description: 'Safety Helmet — MSA V-Gard, Yellow (Workers)',
    category: 'ppe',
    manufacturer: 'MSA Safety',
    unit: 'each',
    currentStock: 210,
    minStockLevel: 100,
    maxStockLevel: 400,
    reorderPoint: 120,
    reorderQty: 200,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'A-01-02',
    unitCostSAR: 58,
    totalValueSAR: 12180,
    lastReceivedDate: '2026-01-20',
    lastIssuedDate: '2026-02-14',
    lastIssuedTo: 'Rig Bravo — New Crew',
    supplierName: 'MSA Safety Arabia',
    supplierPartNumber: 'MSA-10034021',
    leadTimeDays: 7,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['PPE', 'Helmet', 'Worker', 'Head Protection'],
  },
  {
    id: 'WH-PPE-003',
    partNumber: 'ADI-PPE-BOOT-001',
    oemPartNumber: 'HAZ-BLUNDSTONE-990',
    description: 'Safety Boots — Blundstone 990, Steel Toe & Midsole (UK Sizes 7–12)',
    category: 'ppe',
    manufacturer: 'Blundstone',
    unit: 'pair',
    currentStock: 48,
    minStockLevel: 30,
    maxStockLevel: 150,
    reorderPoint: 40,
    reorderQty: 80,
    status: 'low_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'A-02-01',
    unitCostSAR: 420,
    totalValueSAR: 20160,
    lastReceivedDate: '2025-11-10',
    lastIssuedDate: '2026-02-08',
    lastIssuedTo: 'Rig Charlie — New Personnel',
    supplierName: 'Safety Supplies Arabia',
    leadTimeDays: 14,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['PPE', 'Footwear', 'Safety Boots', 'Steel Toe'],
    notes: 'Stock at LOW level — reorder required.',
  },
  {
    id: 'WH-PPE-004',
    partNumber: 'ADI-PPE-GLOVE-001',
    oemPartNumber: 'ANS-HVY-MECH-L',
    description: 'Mechanic Gloves — Ansell Heavy Duty Mechanical, Size L',
    category: 'ppe',
    manufacturer: 'Ansell',
    unit: 'pair',
    currentStock: 320,
    minStockLevel: 150,
    maxStockLevel: 600,
    reorderPoint: 200,
    reorderQty: 300,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'A-03-01',
    unitCostSAR: 38,
    totalValueSAR: 12160,
    lastReceivedDate: '2026-01-15',
    lastIssuedDate: '2026-02-20',
    lastIssuedTo: 'Rig Alpha — General Stock',
    supplierName: 'Safety Supplies Arabia',
    leadTimeDays: 7,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['PPE', 'Gloves', 'Mechanical'],
  },
  {
    id: 'WH-PPE-005',
    partNumber: 'ADI-PPE-VEST-HV-001',
    oemPartNumber: '3M-HV-VEST-CLASS2',
    description: 'High Visibility Vest — 3M Class 2, Orange/Yellow (sizes M, L, XL, XXL)',
    category: 'ppe',
    manufacturer: '3M',
    unit: 'each',
    currentStock: 180,
    minStockLevel: 80,
    maxStockLevel: 300,
    reorderPoint: 100,
    reorderQty: 150,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'A-03-02',
    unitCostSAR: 42,
    totalValueSAR: 7560,
    lastReceivedDate: '2025-12-01',
    supplierName: 'Safety Supplies Arabia',
    leadTimeDays: 7,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['PPE', 'HiVis', 'Vest'],
  },
  {
    id: 'WH-PPE-006',
    partNumber: 'ADI-PPE-H2S-001',
    oemPartNumber: 'MSA-ALTAIR-5X',
    description: 'H2S/LEL/CO Personal Gas Monitor — MSA Altair 5X Multi-Gas',
    category: 'ppe',
    manufacturer: 'MSA Safety',
    unit: 'each',
    currentStock: 22,
    minStockLevel: 20,
    maxStockLevel: 60,
    reorderPoint: 25,
    reorderQty: 20,
    status: 'low_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'B-01-01',
    unitCostSAR: 2850,
    totalValueSAR: 62700,
    lastReceivedDate: '2025-10-05',
    lastIssuedDate: '2026-01-20',
    lastIssuedTo: 'Rig Alpha — New Crew',
    supplierName: 'MSA Safety Arabia',
    supplierPartNumber: 'MSA-10116924',
    leadTimeDays: 21,
    isCriticalSpare: true,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['PPE', 'Gas Monitor', 'H2S', 'LEL', 'MSA Altair 5X', 'Critical'],
    notes: 'Stock approaching minimum. Annual calibration required for all units.',
  },
  {
    id: 'WH-PPE-007',
    partNumber: 'ADI-PPE-SCBA-001',
    oemPartNumber: 'MSA-AUER-AX2100',
    description: 'Self-Contained Breathing Apparatus (SCBA) — MSA AX2100 with 60-min cylinder',
    category: 'safety_equipment',
    manufacturer: 'MSA Safety',
    unit: 'set',
    currentStock: 18,
    minStockLevel: 15,
    maxStockLevel: 30,
    reorderPoint: 18,
    reorderQty: 12,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'B-01-02',
    unitCostSAR: 9800,
    totalValueSAR: 176400,
    lastReceivedDate: '2025-08-10',
    supplierName: 'MSA Safety Arabia',
    leadTimeDays: 30,
    isCriticalSpare: true,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['SCBA', 'Breathing Apparatus', 'Emergency', 'Critical'],
  },
  {
    id: 'WH-PPE-008',
    partNumber: 'ADI-PPE-GOGGLE-001',
    description: 'Chemical Splash Goggles — Honeywell Uvex Stealth',
    category: 'ppe',
    manufacturer: 'Honeywell Uvex',
    unit: 'each',
    currentStock: 95,
    minStockLevel: 40,
    maxStockLevel: 200,
    reorderPoint: 50,
    reorderQty: 100,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'A-04-01',
    unitCostSAR: 35,
    totalValueSAR: 3325,
    lastReceivedDate: '2025-12-01',
    supplierName: 'Safety Supplies Arabia',
    leadTimeDays: 7,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['PPE', 'Eye Protection', 'Chemical', 'Goggles'],
  },

  // ── WELL CONTROL SPARES ──────────────────────────────────────────────
  {
    id: 'WH-WCS-001',
    partNumber: 'ADI-WCS-RAMBLK-001',
    oemPartNumber: 'NOV-SL-RAMBLK-13-10K-PIPE',
    description: 'BOP Pipe Ram Block Assembly — Shaffer 13-5/8" 10,000 PSI (for 5" DP)',
    category: 'spares_well_control',
    manufacturer: 'National Oilwell Varco (Shaffer)',
    unit: 'set',
    currentStock: 3,
    minStockLevel: 2,
    maxStockLevel: 6,
    reorderPoint: 2,
    reorderQty: 2,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'C-01-01',
    unitCostSAR: 48500,
    totalValueSAR: 145500,
    lastReceivedDate: '2025-08-20',
    supplierName: 'NOV Process & Flow Technologies',
    supplierPartNumber: 'NOV-SL-PIPE-5IN-10K',
    leadTimeDays: 45,
    isCriticalSpare: true,
    applicableRigs: ['AD-201', 'AD-203'],
    tags: ['BOP', 'Ram Block', 'Pipe Ram', 'Shaffer', 'Well Control', 'Critical Spare'],
  },
  {
    id: 'WH-WCS-002',
    partNumber: 'ADI-WCS-RAMBLK-002',
    oemPartNumber: 'NOV-SL-RAMBLK-13-10K-BSR',
    description: 'BOP Blind-Shear Ram Block Assembly — Shaffer 13-5/8" 10,000 PSI',
    category: 'spares_well_control',
    manufacturer: 'National Oilwell Varco (Shaffer)',
    unit: 'set',
    currentStock: 2,
    minStockLevel: 1,
    maxStockLevel: 4,
    reorderPoint: 1,
    reorderQty: 2,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'C-01-02',
    unitCostSAR: 125000,
    totalValueSAR: 250000,
    lastReceivedDate: '2024-09-01',
    supplierName: 'NOV Process & Flow Technologies',
    leadTimeDays: 90,
    isCriticalSpare: true,
    applicableRigs: ['AD-201', 'AD-203'],
    tags: ['BOP', 'Ram Block', 'Blind-Shear', 'Shaffer', 'Well Control', 'Critical Spare'],
  },
  {
    id: 'WH-WCS-003',
    partNumber: 'ADI-WCS-SEALKITBOP-001',
    oemPartNumber: 'NOV-SL-SEAL-KIT-13-10K',
    description: 'BOP Full Seal Kit — Shaffer 13-5/8" 10,000 PSI (all elastomers)',
    category: 'spares_well_control',
    manufacturer: 'National Oilwell Varco (Shaffer)',
    unit: 'set',
    currentStock: 2,
    minStockLevel: 1,
    maxStockLevel: 4,
    reorderPoint: 2,
    reorderQty: 2,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'C-01-03',
    unitCostSAR: 35000,
    totalValueSAR: 70000,
    lastReceivedDate: '2025-08-20',
    supplierName: 'NOV Process & Flow Technologies',
    leadTimeDays: 45,
    isCriticalSpare: true,
    applicableRigs: ['AD-201', 'AD-203'],
    tags: ['BOP', 'Seal Kit', 'Elastomers', 'Shaffer', 'Well Control', 'Critical Spare'],
  },
  {
    id: 'WH-WCS-004',
    partNumber: 'ADI-WCS-ACCBLD-001',
    oemPartNumber: 'NOV-ACC-BLADDER-3GAL',
    description: 'BOP Accumulator Bladder — 3-gallon Nitrogen Pre-Charge (for Shaffer & Cameron BOP)',
    category: 'spares_well_control',
    manufacturer: 'National Oilwell Varco',
    unit: 'each',
    currentStock: 24,
    minStockLevel: 12,
    maxStockLevel: 48,
    reorderPoint: 15,
    reorderQty: 24,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'C-02-01',
    unitCostSAR: 850,
    totalValueSAR: 20400,
    lastReceivedDate: '2025-01-05',
    supplierName: 'NOV Process & Flow Technologies',
    leadTimeDays: 21,
    isCriticalSpare: true,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['BOP', 'Accumulator', 'Bladder', 'Well Control', 'Critical Spare'],
  },

  // ── MECHANICAL SPARES ──────────────────────────────────────────────
  {
    id: 'WH-MEC-001',
    partNumber: 'ADI-MEC-LINER-001',
    oemPartNumber: 'NAT-12P-LIN-065',
    description: 'Mud Pump Liner & Piston Assembly — National 12-P-160, 6.5" Chrome Carbide',
    category: 'spares_mechanical',
    manufacturer: 'National Oilwell Varco',
    unit: 'set',
    currentStock: 1,
    minStockLevel: 3,
    maxStockLevel: 9,
    reorderPoint: 3,
    reorderQty: 3,
    status: 'low_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'D-01-01',
    unitCostSAR: 12500,
    totalValueSAR: 12500,
    lastReceivedDate: '2025-06-10',
    lastIssuedDate: '2025-11-20',
    lastIssuedTo: 'Rig Alpha — MDP-001 PM',
    supplierName: 'NOV Parts & Aftermarket',
    supplierPartNumber: 'NOV-12P-6.5-CC-SET',
    leadTimeDays: 14,
    isCriticalSpare: true,
    applicableRigs: ['AD-201'],
    tags: ['Mud Pump', 'Liner', 'Piston', 'National 12-P-160', 'Critical Spare'],
    notes: 'DRQ-2026-006 raised — 3 additional sets on order. Current stock INSUFFICIENT for upcoming planned replacement on MDP-001.',
  },
  {
    id: 'WH-MEC-002',
    partNumber: 'ADI-MEC-LINER-002',
    oemPartNumber: 'NAT-12P-LIN-055',
    description: 'Mud Pump Liner & Piston Assembly — National 12-P-160, 5.5" Chrome Carbide',
    category: 'spares_mechanical',
    manufacturer: 'National Oilwell Varco',
    unit: 'set',
    currentStock: 4,
    minStockLevel: 2,
    maxStockLevel: 8,
    reorderPoint: 3,
    reorderQty: 4,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'D-01-02',
    unitCostSAR: 11800,
    totalValueSAR: 47200,
    lastReceivedDate: '2025-09-01',
    supplierName: 'NOV Parts & Aftermarket',
    leadTimeDays: 14,
    isCriticalSpare: true,
    applicableRigs: ['AD-201'],
    tags: ['Mud Pump', 'Liner', 'Piston', 'National 12-P-160', 'Critical Spare'],
  },
  {
    id: 'WH-MEC-003',
    partNumber: 'ADI-MEC-MUDPMPVLV-001',
    oemPartNumber: 'NAT-12P-VALVE-SET',
    description: 'Mud Pump Valve Assembly — National 12-P-160 (suction & discharge, complete set of 6)',
    category: 'spares_mechanical',
    manufacturer: 'National Oilwell Varco',
    unit: 'set',
    currentStock: 6,
    minStockLevel: 3,
    maxStockLevel: 12,
    reorderPoint: 4,
    reorderQty: 6,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'D-01-03',
    unitCostSAR: 8200,
    totalValueSAR: 49200,
    lastReceivedDate: '2025-10-01',
    supplierName: 'NOV Parts & Aftermarket',
    leadTimeDays: 14,
    isCriticalSpare: true,
    applicableRigs: ['AD-201'],
    tags: ['Mud Pump', 'Valve Assembly', 'National 12-P-160'],
  },
  {
    id: 'WH-MEC-004',
    partNumber: 'ADI-MEC-TDS-FILTER-001',
    oemPartNumber: 'NOV-60220-0000',
    description: 'Top Drive Gearbox Oil Filter Element — Varco TDS-11SA (OEM 5-micron absolute)',
    category: 'spares_mechanical',
    manufacturer: 'National Oilwell Varco',
    unit: 'each',
    currentStock: 8,
    minStockLevel: 4,
    maxStockLevel: 20,
    reorderPoint: 6,
    reorderQty: 8,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'D-02-01',
    unitCostSAR: 1850,
    totalValueSAR: 14800,
    lastReceivedDate: '2025-02-01',
    lastIssuedDate: '2025-01-08',
    lastIssuedTo: 'Rig Alpha — Emergency NCO-2025-001',
    supplierName: 'NOV Parts & Aftermarket',
    supplierPartNumber: 'NOV-60220-0000',
    leadTimeDays: 21,
    isCriticalSpare: true,
    applicableRigs: ['AD-201', 'AD-202'],
    tags: ['Top Drive', 'Filter', 'Gearbox', 'TDS-11SA', 'OEM', 'Critical Spare'],
    notes: 'OEM PART NUMBER MANDATORY — do not substitute. See CAPA-2025-002.',
  },
  {
    id: 'WH-MEC-005',
    partNumber: 'ADI-MEC-RTBBRG-001',
    oemPartNumber: 'SKF-23256-CACK-W33',
    description: 'Rotary Table Spherical Roller Bearing — SKF 23256 CACK/W33 (NAT 14-P-220 equivalent)',
    category: 'spares_mechanical',
    manufacturer: 'SKF',
    unit: 'each',
    currentStock: 1,
    minStockLevel: 1,
    maxStockLevel: 3,
    reorderPoint: 1,
    reorderQty: 2,
    status: 'low_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'D-02-02',
    unitCostSAR: 22000,
    totalValueSAR: 22000,
    lastReceivedDate: '2026-02-26',
    lastIssuedDate: '2026-02-26',
    lastIssuedTo: 'Rig Alpha — Emergency MOC-2026-004',
    supplierName: 'SKF Saudi Arabia',
    supplierPartNumber: 'SKF-23256-CACK-W33',
    leadTimeDays: 3,
    isCriticalSpare: true,
    applicableRigs: ['AD-201'],
    tags: ['Rotary Table', 'Bearing', 'SKF', 'Emergency Spare', 'Critical Spare'],
    notes: 'Last unit used in emergency MOC-2026-004. Reorder in progress.',
  },
  {
    id: 'WH-MEC-006',
    partNumber: 'ADI-MEC-DRALINE-001',
    oemPartNumber: 'WR-158-6x19-IWRC',
    description: 'Drilling Line — 1-5/8" 6x19 IWRC API Wire Rope (per 300m spool)',
    category: 'spares_mechanical',
    manufacturer: 'Wire Rope Industries',
    unit: 'spool',
    currentStock: 3,
    minStockLevel: 2,
    maxStockLevel: 6,
    reorderPoint: 2,
    reorderQty: 2,
    status: 'in_stock',
    location: 'Dammam Base Warehouse — Outdoor Lay-Down',
    binLocation: 'EXT-01',
    unitCostSAR: 185000,
    totalValueSAR: 555000,
    lastReceivedDate: '2025-07-15',
    supplierName: 'Wire Rope Industries Ltd',
    leadTimeDays: 30,
    isCriticalSpare: true,
    applicableRigs: ['AD-201', 'AD-202'],
    tags: ['Drilling Line', 'Wire Rope', '1-5/8"', 'IWRC', 'Critical Spare'],
  },
  {
    id: 'WH-MEC-007',
    partNumber: 'ADI-MEC-SHAKER-SCREEN-001',
    oemPartNumber: 'DEC-FLC500-SCR-API100',
    description: 'Shale Shaker Screen — Derrick FLC 500 / FLC 513, API 100 mesh (panel)',
    category: 'spares_mechanical',
    manufacturer: 'Derrick Equipment Company',
    unit: 'each',
    currentStock: 45,
    minStockLevel: 20,
    maxStockLevel: 100,
    reorderPoint: 25,
    reorderQty: 40,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'D-03-01',
    unitCostSAR: 380,
    totalValueSAR: 17100,
    lastReceivedDate: '2026-01-10',
    lastIssuedDate: '2024-12-14',
    lastIssuedTo: 'Rig Charlie — Screen Replacement REQ-2024-165',
    supplierName: 'Derrick Equipment ME',
    leadTimeDays: 14,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['Shale Shaker', 'Screen', 'Derrick FLC 500', 'API 100', 'Solids Control'],
  },
  {
    id: 'WH-MEC-008',
    partNumber: 'ADI-MEC-GENERATOR-OIL-001',
    oemPartNumber: 'CAT-DEO-15W40-DRUM',
    description: 'Caterpillar Engine Oil — DEO-ULS 15W-40 (205-litre drum)',
    category: 'consumables',
    manufacturer: 'Caterpillar',
    unit: 'drum',
    currentStock: 18,
    minStockLevel: 8,
    maxStockLevel: 40,
    reorderPoint: 10,
    reorderQty: 12,
    status: 'in_stock',
    location: 'Dammam Base Warehouse — Chemical Store',
    binLocation: 'E-01-01',
    unitCostSAR: 1850,
    totalValueSAR: 33300,
    lastReceivedDate: '2025-12-10',
    supplierName: 'Caterpillar Arabia',
    leadTimeDays: 7,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['Engine Oil', 'Caterpillar', 'Generator', 'Lubricant', '15W-40'],
  },

  // ── DRILL STRING COMPONENTS ────────────────────────────────────────
  {
    id: 'WH-DS-001',
    partNumber: 'ADI-DS-DP5-G105-001',
    oemPartNumber: 'PIPE-5-19.5-G105-DS1',
    description: 'Drill Pipe — 5" 19.50 ppf G-105 DS1 Category 2 Premium Used (per joint)',
    category: 'drill_string',
    manufacturer: 'Vallourec / Tenaris',
    unit: 'joint',
    currentStock: 48,
    minStockLevel: 20,
    maxStockLevel: 100,
    reorderPoint: 25,
    reorderQty: 30,
    status: 'in_stock',
    location: 'Dammam Base — Pipe Rack',
    binLocation: 'PTRACK-A-01',
    unitCostSAR: 22000,
    totalValueSAR: 1056000,
    lastReceivedDate: '2025-09-15',
    supplierName: 'Vallourec Drilling Products',
    leadTimeDays: 60,
    isCriticalSpare: true,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['Drill Pipe', '5"', 'G-105', 'DS1', 'Drill String'],
  },
  {
    id: 'WH-DS-002',
    partNumber: 'ADI-DS-SAVESUB-001',
    oemPartNumber: 'SSUB-658-APIIF-DS1CAT2',
    description: 'Saver Sub — 6-5/8" API IF Box x Pin, DS1 Category 2',
    category: 'drill_string',
    manufacturer: 'Grant Prideco',
    unit: 'each',
    currentStock: 4,
    minStockLevel: 3,
    maxStockLevel: 8,
    reorderPoint: 3,
    reorderQty: 3,
    status: 'in_stock',
    location: 'Dammam Base — Pipe Rack',
    binLocation: 'PTRACK-B-01',
    unitCostSAR: 28500,
    totalValueSAR: 114000,
    lastReceivedDate: '2025-02-01',
    supplierName: 'NOV Grant Prideco',
    leadTimeDays: 30,
    isCriticalSpare: true,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['Saver Sub', '6-5/8"', 'API IF', 'DS1', 'Drill String'],
    notes: 'One unit scrapped per NCO-2024-042. Stock replenished.',
  },
  {
    id: 'WH-DS-003',
    partNumber: 'ADI-DS-DRILLBIT-PDC-001',
    oemPartNumber: 'SB-SDi616-1214',
    description: 'PDC Drill Bit — Smith Bits SDi616, 12-1/4" (rental basis, Halliburton)',
    category: 'drill_string',
    manufacturer: 'Smith Bits (Halliburton)',
    unit: 'each',
    currentStock: 2,
    minStockLevel: 1,
    maxStockLevel: 4,
    reorderPoint: 1,
    reorderQty: 2,
    status: 'in_stock',
    location: 'Rig Alpha — Pipe Deck',
    binLocation: 'AD-201-DECK-BIT',
    unitCostSAR: 0,
    totalValueSAR: 0,
    lastReceivedDate: '2025-10-15',
    supplierName: 'Halliburton Drilling Services',
    leadTimeDays: 5,
    isCriticalSpare: true,
    applicableRigs: ['AD-201'],
    tags: ['Drill Bit', 'PDC', 'Smith Bits', '12-1/4"', 'Rental'],
    notes: 'Rental basis — tracked for accountability. Cost SAR 85,000/bit + per-meter charge.',
  },
  {
    id: 'WH-DS-004',
    partNumber: 'ADI-DS-DRILLBIT-TRI-001',
    oemPartNumber: 'SB-IU74-174',
    description: 'Tricone Drill Bit — Smith Bits IADC 537, 17-1/2" (rental basis)',
    category: 'drill_string',
    manufacturer: 'Smith Bits (Halliburton)',
    unit: 'each',
    currentStock: 2,
    minStockLevel: 1,
    maxStockLevel: 4,
    reorderPoint: 1,
    reorderQty: 2,
    status: 'in_stock',
    location: 'Rig Bravo — Pipe Deck',
    binLocation: 'AD-202-DECK-BIT',
    unitCostSAR: 0,
    totalValueSAR: 0,
    lastReceivedDate: '2025-11-01',
    supplierName: 'Halliburton Drilling Services',
    leadTimeDays: 5,
    isCriticalSpare: true,
    applicableRigs: ['AD-202'],
    tags: ['Drill Bit', 'Tricone', 'Smith Bits', '17-1/2"', 'Rental'],
  },

  // ── MUD CHEMICALS ─────────────────────────────────────────────────
  {
    id: 'WH-CHM-001',
    partNumber: 'ADI-CHM-BARITE-001',
    oemPartNumber: 'MAG-BARITE-50KG',
    description: 'Barite Weighting Agent — Magcobar API Grade (50 kg bag)',
    category: 'mud_chemicals',
    manufacturer: 'Magcobar (Schlumberger)',
    unit: 'bag',
    currentStock: 2400,
    minStockLevel: 1000,
    maxStockLevel: 5000,
    reorderPoint: 1200,
    reorderQty: 2000,
    status: 'in_stock',
    location: 'Dammam Base — Chemical Warehouse',
    binLocation: 'CHEM-A-01',
    unitCostSAR: 85,
    totalValueSAR: 204000,
    lastReceivedDate: '2026-01-20',
    supplierName: 'Schlumberger Supply Chain',
    leadTimeDays: 10,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['Mud Chemical', 'Barite', 'Weighting Agent', 'WBM', 'OBM'],
  },
  {
    id: 'WH-CHM-002',
    partNumber: 'ADI-CHM-KCL-001',
    oemPartNumber: 'KCL-INDUSTRIAL-50KG',
    description: 'Potassium Chloride (KCl) — Industrial Grade (50 kg bag)',
    category: 'mud_chemicals',
    manufacturer: 'SABIC / Mosaic',
    unit: 'bag',
    currentStock: 420,
    minStockLevel: 200,
    maxStockLevel: 1000,
    reorderPoint: 250,
    reorderQty: 400,
    status: 'in_stock',
    location: 'Dammam Base — Chemical Warehouse',
    binLocation: 'CHEM-A-02',
    unitCostSAR: 45,
    totalValueSAR: 18900,
    lastReceivedDate: '2026-02-01',
    supplierName: 'SABIC Trading',
    leadTimeDays: 5,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202'],
    tags: ['Mud Chemical', 'KCl', 'Shale Inhibitor', 'WBM'],
  },
  {
    id: 'WH-CHM-003',
    partNumber: 'ADI-CHM-PAC-LV-001',
    description: 'Poly Anionic Cellulose (PAC-LV) — Fluid Loss Control (25 kg bag)',
    category: 'mud_chemicals',
    manufacturer: 'Halliburton Baroid',
    unit: 'bag',
    currentStock: 280,
    minStockLevel: 100,
    maxStockLevel: 500,
    reorderPoint: 120,
    reorderQty: 200,
    status: 'in_stock',
    location: 'Dammam Base — Chemical Warehouse',
    binLocation: 'CHEM-A-03',
    unitCostSAR: 120,
    totalValueSAR: 33600,
    lastReceivedDate: '2025-12-20',
    supplierName: 'Halliburton Drilling Fluids',
    leadTimeDays: 7,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['Mud Chemical', 'PAC', 'Fluid Loss Control', 'WBM'],
  },
  {
    id: 'WH-CHM-004',
    partNumber: 'ADI-CHM-BIOCIDE-001',
    oemPartNumber: 'BH-BWT750-50-200L',
    description: 'Biocide BWT-750 — Baker Hughes 50% concentration (200 litre drum)',
    category: 'mud_chemicals',
    manufacturer: 'Baker Hughes',
    unit: 'drum',
    currentStock: 8,
    minStockLevel: 4,
    maxStockLevel: 20,
    reorderPoint: 5,
    reorderQty: 8,
    status: 'in_stock',
    location: 'Dammam Base — Chemical Warehouse',
    binLocation: 'CHEM-B-01',
    unitCostSAR: 2800,
    totalValueSAR: 22400,
    lastReceivedDate: '2025-03-01',
    lastIssuedDate: '2025-02-15',
    lastIssuedTo: 'Rig Alpha (NCO-2025-004 — wrong concentration batch quarantined)',
    supplierName: 'Baker Hughes ME',
    leadTimeDays: 14,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['Mud Chemical', 'Biocide', 'BWT-750', 'Baker Hughes'],
    notes: 'Specify 50% concentration on all POs. 25% concentration batch received in error — NCO-2025-004.',
  },

  // ── CEMENT CHEMICALS ─────────────────────────────────────────────
  {
    id: 'WH-CEM-001',
    partNumber: 'ADI-CEM-CLASS-G-001',
    description: 'API Class G Cement (High Sulphate Resistant) — 50 kg bag',
    category: 'cement_chemicals',
    manufacturer: 'Yamama Cement / Saudi Cement',
    unit: 'bag',
    currentStock: 3200,
    minStockLevel: 1500,
    maxStockLevel: 8000,
    reorderPoint: 2000,
    reorderQty: 4000,
    status: 'in_stock',
    location: 'Dammam Base — Cement Store (Bulk silo)',
    binLocation: 'SILO-01',
    unitCostSAR: 28,
    totalValueSAR: 89600,
    lastReceivedDate: '2026-01-25',
    supplierName: 'Yamama Cement Company',
    leadTimeDays: 3,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['Cement', 'API Class G', 'HSR', 'Well Cementing'],
  },

  // ── TOOLS ─────────────────────────────────────────────────────────
  {
    id: 'WH-TOOL-001',
    partNumber: 'ADI-TOOL-PWRENCH-001',
    description: 'Pipe Wrench — Ridgid 36" Heavy Duty (Aluminium Handle)',
    category: 'tools_hand',
    manufacturer: 'Ridgid',
    unit: 'each',
    currentStock: 14,
    minStockLevel: 6,
    maxStockLevel: 30,
    reorderPoint: 8,
    reorderQty: 10,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'F-01-01',
    unitCostSAR: 680,
    totalValueSAR: 9520,
    lastReceivedDate: '2025-08-10',
    supplierName: 'Industrial Tools Arabia',
    leadTimeDays: 7,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['Tools', 'Pipe Wrench', 'Ridgid', '36"'],
  },
  {
    id: 'WH-TOOL-002',
    partNumber: 'ADI-TOOL-BREAKOUTTONS-001',
    description: 'Breakout Tong — B.J. Operations 10" HWDP',
    category: 'tools_hand',
    manufacturer: 'BJ Services (Baker Hughes)',
    unit: 'each',
    currentStock: 3,
    minStockLevel: 2,
    maxStockLevel: 8,
    reorderPoint: 2,
    reorderQty: 3,
    status: 'in_stock',
    location: 'Rig Alpha — Tool Store',
    binLocation: 'AD-201-TOOL-01',
    unitCostSAR: 8500,
    totalValueSAR: 25500,
    lastReceivedDate: '2025-05-01',
    supplierName: 'Baker Hughes Rental',
    leadTimeDays: 5,
    isCriticalSpare: false,
    applicableRigs: ['AD-201'],
    tags: ['Tools', 'Breakout Tong', 'HWDP', 'Drill Floor'],
  },
  {
    id: 'WH-TOOL-003',
    partNumber: 'ADI-TOOL-TORQUEWRENCH-001',
    description: 'Hydraulic Torque Wrench — Enerpac HMT-Series, 1,200 ft-lb (for flange bolts)',
    category: 'tools_power',
    manufacturer: 'Enerpac',
    unit: 'set',
    currentStock: 2,
    minStockLevel: 1,
    maxStockLevel: 4,
    reorderPoint: 2,
    reorderQty: 2,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'F-02-01',
    unitCostSAR: 18500,
    totalValueSAR: 37000,
    lastReceivedDate: '2024-06-01',
    supplierName: 'Enerpac ME',
    leadTimeDays: 21,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['Tools', 'Torque Wrench', 'Hydraulic', 'Enerpac'],
  },
  {
    id: 'WH-TOOL-004',
    partNumber: 'ADI-TOOL-FIREEXT-CO2-001',
    description: 'CO2 Fire Extinguisher — 6 kg (Kidde Pro)',
    category: 'safety_equipment',
    manufacturer: 'Kidde',
    unit: 'each',
    currentStock: 32,
    minStockLevel: 20,
    maxStockLevel: 80,
    reorderPoint: 25,
    reorderQty: 30,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'G-01-01',
    unitCostSAR: 285,
    totalValueSAR: 9120,
    lastReceivedDate: '2025-10-01',
    supplierName: 'Protec Fire & Safety',
    leadTimeDays: 7,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['Fire Extinguisher', 'CO2', '6kg', 'Safety', 'Kidde'],
  },
  {
    id: 'WH-TOOL-005',
    partNumber: 'ADI-TOOL-FIREEXT-DCP-001',
    description: 'Dry Chemical Powder (ABC) Fire Extinguisher — 9 kg',
    category: 'safety_equipment',
    manufacturer: 'Flamestop',
    unit: 'each',
    currentStock: 44,
    minStockLevel: 25,
    maxStockLevel: 100,
    reorderPoint: 30,
    reorderQty: 40,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'G-01-02',
    unitCostSAR: 195,
    totalValueSAR: 8580,
    lastReceivedDate: '2025-10-01',
    supplierName: 'Protec Fire & Safety',
    leadTimeDays: 7,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['Fire Extinguisher', 'DCP', 'ABC', '9kg', 'Safety'],
  },

  // ── TUBULAR GOODS ─────────────────────────────────────────────────
  {
    id: 'WH-TUB-001',
    partNumber: 'ADI-TUB-CASING-95-001',
    description: '9-5/8" 47.00 ppf K-55 BTC Casing (per joint ~9.5m)',
    category: 'tubular_goods',
    manufacturer: 'Tenaris',
    unit: 'joint',
    currentStock: 62,
    minStockLevel: 20,
    maxStockLevel: 120,
    reorderPoint: 30,
    reorderQty: 60,
    status: 'in_stock',
    location: 'Dammam Base — Tubular Rack',
    binLocation: 'PTRACK-CAS-01',
    unitCostSAR: 18500,
    totalValueSAR: 1147000,
    lastReceivedDate: '2025-11-15',
    supplierName: 'Tenaris ME',
    leadTimeDays: 45,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['Casing', '9-5/8"', 'K-55', 'BTC', 'Tenaris'],
  },
  {
    id: 'WH-TUB-002',
    partNumber: 'ADI-TUB-CASING-7-001',
    description: '7" 26.00 ppf L-80 BTC Production Casing (per joint ~9.5m)',
    category: 'tubular_goods',
    manufacturer: 'Tenaris',
    unit: 'joint',
    currentStock: 88,
    minStockLevel: 30,
    maxStockLevel: 200,
    reorderPoint: 40,
    reorderQty: 80,
    status: 'in_stock',
    location: 'Dammam Base — Tubular Rack',
    binLocation: 'PTRACK-CAS-02',
    unitCostSAR: 8200,
    totalValueSAR: 721600,
    lastReceivedDate: '2025-10-20',
    supplierName: 'Tenaris ME',
    leadTimeDays: 45,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['Casing', '7"', 'L-80', 'BTC', 'Production Casing'],
  },

  // ── ELECTRICAL SPARES ─────────────────────────────────────────────
  {
    id: 'WH-ELC-001',
    partNumber: 'ADI-ELC-VARSPD-DRIVE-001',
    description: 'Variable Speed Drive (VSD) Module — ABB ACS880-37, 500 kW, 690V',
    category: 'spares_electrical',
    manufacturer: 'ABB',
    unit: 'each',
    currentStock: 1,
    minStockLevel: 1,
    maxStockLevel: 3,
    reorderPoint: 1,
    reorderQty: 1,
    status: 'in_stock',
    location: 'Dammam Base Warehouse — Electrical Store',
    binLocation: 'H-01-01',
    unitCostSAR: 185000,
    totalValueSAR: 185000,
    lastReceivedDate: '2024-08-01',
    supplierName: 'ABB Saudi Arabia',
    leadTimeDays: 60,
    isCriticalSpare: true,
    applicableRigs: ['AD-201', 'AD-202'],
    tags: ['VSD', 'ABB', 'Electrical', 'Critical Spare', 'Top Drive', 'Power System'],
  },
  {
    id: 'WH-ELC-002',
    partNumber: 'ADI-ELC-SCR-MODULE-001',
    description: 'SCR Module — Silicon Controlled Rectifier Assembly, 1,000A 690V',
    category: 'spares_electrical',
    manufacturer: 'Siemens',
    unit: 'each',
    currentStock: 2,
    minStockLevel: 1,
    maxStockLevel: 4,
    reorderPoint: 2,
    reorderQty: 2,
    status: 'in_stock',
    location: 'Dammam Base Warehouse — Electrical Store',
    binLocation: 'H-01-02',
    unitCostSAR: 95000,
    totalValueSAR: 190000,
    lastReceivedDate: '2025-03-10',
    supplierName: 'Siemens Saudi Arabia',
    leadTimeDays: 45,
    isCriticalSpare: true,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['SCR', 'Siemens', 'Electrical', 'Critical Spare', 'Power System'],
  },

  // ── CONSUMABLES ───────────────────────────────────────────────────
  {
    id: 'WH-CON-001',
    partNumber: 'ADI-CON-GEAROIL-220-001',
    description: 'Gear Oil — ISO VG 220 (20 litre container)',
    category: 'consumables',
    manufacturer: 'Shell',
    unit: 'each',
    currentStock: 38,
    minStockLevel: 20,
    maxStockLevel: 80,
    reorderPoint: 25,
    reorderQty: 30,
    status: 'in_stock',
    location: 'Dammam Base — Lubricant Store',
    binLocation: 'E-02-01',
    unitCostSAR: 320,
    totalValueSAR: 12160,
    lastReceivedDate: '2025-12-15',
    supplierName: 'Shell Lubricants Arabia',
    leadTimeDays: 5,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202'],
    tags: ['Gear Oil', 'ISO VG 220', 'Shell', 'Top Drive', 'Lubricant'],
  },
  {
    id: 'WH-CON-002',
    partNumber: 'ADI-CON-THREADCOMP-001',
    description: 'Copper-Based Thread Compound (API Modified) — 5 kg tin',
    category: 'consumables',
    manufacturer: 'Thomas & Betts (Jet-Lube)',
    unit: 'each',
    currentStock: 64,
    minStockLevel: 20,
    maxStockLevel: 100,
    reorderPoint: 25,
    reorderQty: 40,
    status: 'in_stock',
    location: 'Dammam Base Warehouse',
    binLocation: 'E-03-01',
    unitCostSAR: 185,
    totalValueSAR: 11840,
    lastReceivedDate: '2025-10-15',
    supplierName: 'Jet-Lube ME',
    leadTimeDays: 7,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['Thread Compound', 'API Dope', 'Copper-Based', 'Consumable'],
  },
  {
    id: 'WH-CON-003',
    partNumber: 'ADI-CON-DIESEL-FUEL-001',
    description: 'Diesel Fuel — EN590 Grade (per 1,000 litre road tanker delivery)',
    category: 'consumables',
    manufacturer: 'Saudi Aramco Downstream',
    unit: 'litre',
    currentStock: 185000,
    minStockLevel: 80000,
    maxStockLevel: 500000,
    reorderPoint: 100000,
    reorderQty: 150000,
    status: 'in_stock',
    location: 'All Rig Sites (combined)',
    binLocation: 'FUEL-TANK',
    unitCostSAR: 0.75,
    totalValueSAR: 138750,
    lastReceivedDate: '2026-02-22',
    supplierName: 'Saudi Aramco Downstream / Shuraa Transport',
    leadTimeDays: 2,
    isCriticalSpare: false,
    applicableRigs: ['AD-201', 'AD-202', 'AD-203'],
    tags: ['Diesel', 'Fuel', 'EN590', 'Generator', 'Consumable'],
  },
];

// Summary stats for dashboard
export const WAREHOUSE_SUMMARY = {
  totalItems: INVENTORY_ITEMS.length,
  totalValueSAR: INVENTORY_ITEMS.reduce((sum, item) => sum + item.totalValueSAR, 0),
  lowStockItems: INVENTORY_ITEMS.filter((i) => i.status === 'low_stock').length,
  outOfStockItems: INVENTORY_ITEMS.filter((i) => i.status === 'out_of_stock').length,
  quarantineItems: INVENTORY_ITEMS.filter((i) => i.status === 'quarantine').length,
  criticalSpares: INVENTORY_ITEMS.filter((i) => i.isCriticalSpare).length,
};

export const getItemById = (id: string): InventoryItem | undefined =>
  INVENTORY_ITEMS.find((i) => i.id === id);

export const getItemsByCategory = (category: ItemCategory): InventoryItem[] =>
  INVENTORY_ITEMS.filter((i) => i.category === category);

export const getLowStockItems = (): InventoryItem[] =>
  INVENTORY_ITEMS.filter((i) => i.currentStock <= i.reorderPoint);

export const getCriticalSpares = (): InventoryItem[] =>
  INVENTORY_ITEMS.filter((i) => i.isCriticalSpare);
